package com.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.6-redhat-3
 * 2013-10-15T10:24:28.818+02:00
 * Generated source version: 2.6.6-redhat-3
 * 
 */
@WebService(targetNamespace = "http://housing.com/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://housing.com/", className = "com.ws.client.SayHello")
    @WebMethod
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://housing.com/", className = "com.ws.client.SayHelloResponse")
    public java.lang.String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "initJob", targetNamespace = "http://housing.com/", className = "com.ws.client.InitJob")
    @WebMethod
    @ResponseWrapper(localName = "initJobResponse", targetNamespace = "http://housing.com/", className = "com.ws.client.InitJobResponse")
    public com.ws.client.WebResult initJob(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id,
        @WebParam(name = "metadata", targetNamespace = "")
        byte[] metadata
    );
}
