package webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.6-redhat-3
 * 2013-12-17T10:03:08.859+01:00
 * Generated source version: 2.6.6-redhat-3
 * 
 */
@WebService(targetNamespace = "http://webservices.samples.jboss.org/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHelloParams", targetNamespace = "http://webservices.samples.jboss.org/", className = "webservice.SayHelloParams")
    @WebMethod
    @ResponseWrapper(localName = "sayHelloParamsResponse", targetNamespace = "http://webservices.samples.jboss.org/", className = "webservice.SayHelloParamsResponse")
    public java.lang.String sayHelloParams(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id,
        @WebParam(name = "contents", targetNamespace = "")
        byte[] contents
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://webservices.samples.jboss.org/", className = "webservice.SayHello")
    @WebMethod
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://webservices.samples.jboss.org/", className = "webservice.SayHelloResponse")
    public java.lang.String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
