INSERT INTO `test` (`id`, `name`) VALUES (10280, 'Pralni stroji s prednjim polnjenjem in visoko centrifugo 300G-425G, W 455H');
INSERT INTO `test` (`id`, `name`) VALUES (322, 'Osvežilo sredstvo NOWA pulse pršilo');
INSERT INTO `test` (`id`, `name`) VALUES (303, 'Podajalnik Brisač KATRIN Elektronski');
INSERT INTO `test` (`id`, `name`) VALUES (312, 'Podajalnik sanitarnih vrečk Katrin Ultimatic');
INSERT INTO `test` (`id`, `name`) VALUES (310, 'Podajalnik toaletnega papirja Katrin Ultimatic');
INSERT INTO `test` (`id`, `name`) VALUES (177, 'Surovine za slaščičarstvo');
INSERT INTO `test` (`id`, `name`) VALUES (287, 'Čistilna sredstva in pripomočki za čiščenje');
INSERT INTO `test` (`id`, `name`) VALUES (355, 'Podajalnik brisač v roli »BLUE TECH«');
INSERT INTO `test` (`id`, `name`) VALUES (10202, 'CHUMBY 8');
INSERT INTO `test` (`id`, `name`) VALUES (10250, 'Domača Grappa');
INSERT INTO `test` (`id`, `name`) VALUES (281, ' Gastronorm posoda');
INSERT INTO `test` (`id`, `name`) VALUES (796, ' Gostinska kuhinjska oprema Rabljena, Mont novo mesto');
INSERT INTO `test` (`id`, `name`) VALUES (506, ' Grog');
INSERT INTO `test` (`id`, `name`) VALUES (276, ' Kozarci in izdelki iz stekla');
INSERT INTO `test` (`id`, `name`) VALUES (280, ' Kuhinjski pripomočki');
INSERT INTO `test` (`id`, `name`) VALUES (311, ' Milnik Katrin Ultimatic');
INSERT INTO `test` (`id`, `name`) VALUES (521, ' Pivo Export Pils');
INSERT INTO `test` (`id`, `name`) VALUES (623, ' Poslovna darila');
INSERT INTO `test` (`id`, `name`) VALUES (431, ' Ravioli polnjeni z baziliko Barone');
INSERT INTO `test` (`id`, `name`) VALUES (251, ' Veltins Pilsner ');
INSERT INTO `test` (`id`, `name`) VALUES (3176, '\'EKO premija\' in \'plačilo na obroke\'');
INSERT INTO `test` (`id`, `name`) VALUES (10311, '10% popust na 100% odlično ale pivo ESB');
INSERT INTO `test` (`id`, `name`) VALUES (2369, '100-letna penina - AGROIND VIPAVA 1984');
INSERT INTO `test` (`id`, `name`) VALUES (2548, 'A+ belo - GORIsKA BRDA');
INSERT INTO `test` (`id`, `name`) VALUES (2559, 'A+ rdece - GORIsKA BRDA');
INSERT INTO `test` (`id`, `name`) VALUES (6257, 'ABSINTHE 60% 0.7L');
INSERT INTO `test` (`id`, `name`) VALUES (6179, 'ABSINTHE FLEURS 0.7L');
INSERT INTO `test` (`id`, `name`) VALUES (491, 'ACE');
INSERT INTO `test` (`id`, `name`) VALUES (4915, 'ACE LIMONA RAD. 1.50 PVC');
INSERT INTO `test` (`id`, `name`) VALUES (4917, 'ACE LIMONA RAD. ŠZ 0.50 PVC');
INSERT INTO `test` (`id`, `name`) VALUES (4916, 'ACE LIMONA RAD.NAV.Z.  0.50 PVC ');
INSERT INTO `test` (`id`, `name`) VALUES (13257, 'ACE limona Radenska pet 1.5L');
INSERT INTO `test` (`id`, `name`) VALUES (19354, 'ACE limona Radenska pet 1.5L');
INSERT INTO `test` (`id`, `name`) VALUES (4911, 'ACE TROPIC RAD. 0.50 NAV. Z. PVC');
INSERT INTO `test` (`id`, `name`) VALUES (4912, 'ACE TROPIC RAD. 1.50 PVC');
INSERT INTO `test` (`id`, `name`) VALUES (4913, 'ACE TROPIC RAD. ŠZ. 0.50 PVC');
INSERT INTO `test` (`id`, `name`) VALUES (13258, 'ACE Tropic Radenska pet 0.5L');
INSERT INTO `test` (`id`, `name`) VALUES (19355, 'ACE Tropic Radenska pet 0.5L');
INSERT INTO `test` (`id`, `name`) VALUES (13259, 'ACE tropik Radenska pet 1.5L');
INSERT INTO `test` (`id`, `name`) VALUES (19356, 'ACE tropik Radenska pet 1.5L');
INSERT INTO `test` (`id`, `name`) VALUES (13260, 'ACE z zelenim čajem Radenska pet 1.5L');
INSERT INTO `test` (`id`, `name`) VALUES (19357, 'ACE z zelenim čajem Radenska pet 1.5L');
INSERT INTO `test` (`id`, `name`) VALUES (4919, 'ACE ZELENI ČAJ 0.50 L NAV.Z.PVC');
INSERT INTO `test` (`id`, `name`) VALUES (4918, 'ACE ZELENI ČAJ RAD. 1.50 PVC');
INSERT INTO `test` (`id`, `name`) VALUES (4920, 'ACE ZELENI ČAJ ŠZ RAD. 0.50 PVC ');
INSERT INTO `test` (`id`, `name`) VALUES (1092, 'Adoptis, Finance');
INSERT INTO `test` (`id`, `name`) VALUES (1091, 'Adoptis, Intrastat');
INSERT INTO `test` (`id`, `name`) VALUES (1090, 'Adoptis, Maloprodaja, Veleprodaja');
INSERT INTO `test` (`id`, `name`) VALUES (1089, 'Adoptis, Pos Blagajna');
INSERT INTO `test` (`id`, `name`) VALUES (1086, 'Adoptis,Blagajna na dotik - PosHero');
INSERT INTO `test` (`id`, `name`) VALUES (159, 'Advantik Bar - blagajna + poslovanje ');
INSERT INTO `test` (`id`, `name`) VALUES (3337, 'Advantik cafe - računalniška blagajna');
INSERT INTO `test` (`id`, `name`) VALUES (3198, 'Advantik Cvetličarna - blagajna + poslovanje');
INSERT INTO `test` (`id`, `name`) VALUES (3200, 'Advantik Fitness - recepcija + poslovanje');
INSERT INTO `test` (`id`, `name`) VALUES (3199, 'Advantik Frizerski salon - blagajna + poslovanje');
INSERT INTO `test` (`id`, `name`) VALUES (3201, 'Advantik Konektor - več poslovnih enot');
INSERT INTO `test` (`id`, `name`) VALUES (160, 'Advantik Restavracija - blagajna + poslovanje ');
INSERT INTO `test` (`id`, `name`) VALUES (3197, 'Advantik Trgovina - blagajna + poslovanje');
INSERT INTO `test` (`id`, `name`) VALUES (7733, 'AJVAR 4KG MT');
INSERT INTO `test` (`id`, `name`) VALUES (8592, 'AJVAR 700G UP KOZ.');
INSERT INTO `test` (`id`, `name`) VALUES (10523, 'Ajvar blagi pražen Podravka koz 0.35kg');
INSERT INTO `test` (`id`, `name`) VALUES (16620, 'Ajvar blagi pražen Podravka koz 0.35kg');
INSERT INTO `test` (`id`, `name`) VALUES (10524, 'Ajvar blagi pražen Podravka koz 0.69kg');
INSERT INTO `test` (`id`, `name`) VALUES (16621, 'Ajvar blagi pražen Podravka koz 0.69kg');
INSERT INTO `test` (`id`, `name`) VALUES (8596, 'AJVAR BLAGI VORI 720G KOZ.');
INSERT INTO `test` (`id`, `name`) VALUES (8608, 'AJVAR BONVITA 4.3KG PLOČ.');
INSERT INTO `test` (`id`, `name`) VALUES (8151, 'AJVAR ETA 4KG PLOČ.');
INSERT INTO `test` (`id`, `name`) VALUES (8589, 'AJVAR MT 360G KOZ.');
INSERT INTO `test` (`id`, `name`) VALUES (7732, 'AJVAR MT 650G KOZ.');
INSERT INTO `test` (`id`, `name`) VALUES (8180, 'AJVAR NEPEKOČ ETA  1KG KOZ.');
INSERT INTO `test` (`id`, `name`) VALUES (8178, 'AJVAR NEPEKOČ ETA 290 G');
INSERT INTO `test` (`id`, `name`) VALUES (10525, 'Ajvar nepekoč pražen Eta ploč 4kg');
INSERT INTO `test` (`id`, `name`) VALUES (16622, 'Ajvar nepekoč pražen Eta ploč 4kg');
INSERT INTO `test` (`id`, `name`) VALUES (10526, 'Ajvar nepekoč pražen Eta UP koz 540g');
INSERT INTO `test` (`id`, `name`) VALUES (16623, 'Ajvar nepekoč pražen Eta UP koz 540g');
INSERT INTO `test` (`id`, `name`) VALUES (10527, 'Ajvar nepekoč pražen Kam inženiring koz 2.5kg');
INSERT INTO `test` (`id`, `name`) VALUES (16624, 'Ajvar nepekoč pražen Kam inženiring koz 2.5kg');
INSERT INTO `test` (`id`, `name`) VALUES (10528, 'Ajvar nepekoč pražen Kam inženiring koz 680g');
INSERT INTO `test` (`id`, `name`) VALUES (16625, 'Ajvar nepekoč pražen Kam inženiring koz 680g');
INSERT INTO `test` (`id`, `name`) VALUES (10529, 'Ajvar nepekoč pražen NaturEta koz 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (16626, 'Ajvar nepekoč pražen NaturEta koz 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (10530, 'Ajvar nepekoč pražen Natureta koz. 190g');
INSERT INTO `test` (`id`, `name`) VALUES (16627, 'Ajvar nepekoč pražen Natureta koz. 190g');
INSERT INTO `test` (`id`, `name`) VALUES (8179, 'AJVAR NEPEKOČI ETA 540G KOZ.');
INSERT INTO `test` (`id`, `name`) VALUES (9903, 'AJVAR NEPEKOČI MERCATOR 650G');
INSERT INTO `test` (`id`, `name`) VALUES (10531, 'Ajvar nepekoči Rio Santo koz 0.56kg');
INSERT INTO `test` (`id`, `name`) VALUES (16628, 'Ajvar nepekoči Rio Santo koz 0.56kg');
INSERT INTO `test` (`id`, `name`) VALUES (10532, 'Ajvar nepekoči Rio Santo koz 2.65kg');
INSERT INTO `test` (`id`, `name`) VALUES (16629, 'Ajvar nepekoči Rio Santo koz 2.65kg');
INSERT INTO `test` (`id`, `name`) VALUES (8177, 'AJVAR PEKOČI 290G');
INSERT INTO `test` (`id`, `name`) VALUES (7731, 'AJVAR PIKANTNI LUTENICA NEGOTINO 360G KOZ.');
INSERT INTO `test` (`id`, `name`) VALUES (8183, 'AJVAR POLPEKOČ ETA 1KG KOZ.');
INSERT INTO `test` (`id`, `name`) VALUES (10533, 'Ajvar polpekoč NaturEta koz. 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (16630, 'Ajvar polpekoč NaturEta koz. 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (8182, 'AJVAR POLPEKOČI 540G ETA');
INSERT INTO `test` (`id`, `name`) VALUES (8181, 'AJVAR POLPEKOČI ETA 290G');
INSERT INTO `test` (`id`, `name`) VALUES (10534, 'Ajvar pražen blagi Mercator koz 0.65kg');
INSERT INTO `test` (`id`, `name`) VALUES (16631, 'Ajvar pražen blagi Mercator koz 0.65kg');
INSERT INTO `test` (`id`, `name`) VALUES (10535, 'Ajvar pražen koz 650g');
INSERT INTO `test` (`id`, `name`) VALUES (16632, 'Ajvar pražen koz 650g');
INSERT INTO `test` (`id`, `name`) VALUES (10536, 'Ajvar pražen polpekoč Natureta koz. 540g');
INSERT INTO `test` (`id`, `name`) VALUES (16633, 'Ajvar pražen polpekoč Natureta koz. 540g');
INSERT INTO `test` (`id`, `name`) VALUES (10537, 'Ajvar praženi KZ Metlika koz 700g');
INSERT INTO `test` (`id`, `name`) VALUES (16634, 'Ajvar praženi KZ Metlika koz 700g');
INSERT INTO `test` (`id`, `name`) VALUES (8580, 'AJVAR PRAŽENI ZORA 700G ');
INSERT INTO `test` (`id`, `name`) VALUES (8598, 'AJVAR VORI 2500 G');
INSERT INTO `test` (`id`, `name`) VALUES (8583, 'AJVAR ZORA 3KG KOZ.');
INSERT INTO `test` (`id`, `name`) VALUES (8579, 'AJVAR ZORA 5KG');
INSERT INTO `test` (`id`, `name`) VALUES (8582, 'AJVAR ZORA 700G');
INSERT INTO `test` (`id`, `name`) VALUES (803, 'Akcija');
INSERT INTO `test` (`id`, `name`) VALUES (3444, 'Akcija avgust 2011');
INSERT INTO `test` (`id`, `name`) VALUES (877, 'Akcijska ponudba');
INSERT INTO `test` (`id`, `name`) VALUES (2925, 'Akcijske cene v maju');
INSERT INTO `test` (`id`, `name`) VALUES (3408, 'AKCIJSKI KATALOG EUROPET d.o.o. / AVGUST 2011');
INSERT INTO `test` (`id`, `name`) VALUES (10264, 'Akcijski letak KZ Metlika ');
INSERT INTO `test` (`id`, `name`) VALUES (3376, 'Alarmna naprava OLYMPIA -  Protect 5080');
INSERT INTO `test` (`id`, `name`) VALUES (2659, 'Albus - PICCINI');
INSERT INTO `test` (`id`, `name`) VALUES (10538, 'Alge morske mešane Seaweed MIX vreč 100g');
INSERT INTO `test` (`id`, `name`) VALUES (16635, 'Alge morske mešane Seaweed MIX vreč 100g');
INSERT INTO `test` (`id`, `name`) VALUES (15227, 'Alkohol čisti (96%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (21324, 'Alkohol čisti (96%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (3691, 'ALKOHOL ZA VLOŽENO SADJE 40% 1L BAUER');
INSERT INTO `test` (`id`, `name`) VALUES (3692, 'ALKOHOL ZA VLOŽENO SADJE 60% 1L BAUER');
INSERT INTO `test` (`id`, `name`) VALUES (3693, 'ALKOHOL ZA VLOŽENO SADJE 80% 1L BAUER');
INSERT INTO `test` (`id`, `name`) VALUES (4350, 'AMARO 18 0.1L');
INSERT INTO `test` (`id`, `name`) VALUES (4351, 'AMARO 18 1L');
INSERT INTO `test` (`id`, `name`) VALUES (4363, 'AMARO MONTENEGRO 23% 0.7L');
INSERT INTO `test` (`id`, `name`) VALUES (4368, 'AMARO RAMAZOTTI 30% 0.03L');
INSERT INTO `test` (`id`, `name`) VALUES (4367, 'AMARO RAMAZOTTI 30% 0.7L ');
INSERT INTO `test` (`id`, `name`) VALUES (4369, 'AMARO RAMAZZOTI 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (4340, 'AMARO ZELIŠČNI 30% PETOVIA 1L');
INSERT INTO `test` (`id`, `name`) VALUES (241, 'Amarula');
INSERT INTO `test` (`id`, `name`) VALUES (10298, 'AMERIŠKI ŠČUREK (Periplaneta americana)');
INSERT INTO `test` (`id`, `name`) VALUES (2524, 'Amfora - KABAJ');
INSERT INTO `test` (`id`, `name`) VALUES (7080, 'ANANAS');
INSERT INTO `test` (`id`, `name`) VALUES (10539, 'Ananas del Monte');
INSERT INTO `test` (`id`, `name`) VALUES (16636, 'Ananas del Monte');
INSERT INTO `test` (`id`, `name`) VALUES (7831, 'ANANAS SUHI KOCKE 150 G');
INSERT INTO `test` (`id`, `name`) VALUES (10540, 'Ananas svež 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (16637, 'Ananas svež 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (9895, 'APARAT  ZA SMETANO MOSA 1L');
INSERT INTO `test` (`id`, `name`) VALUES (22728, 'APARAT AZ SMETANO CARPIGIANI ECOWIP');
INSERT INTO `test` (`id`, `name`) VALUES (3268, 'Aparat HOT-DOG');
INSERT INTO `test` (`id`, `name`) VALUES (3085, 'Aparat za naravne negazirane sokove');
INSERT INTO `test` (`id`, `name`) VALUES (3086, 'Aparat za naravne sadne koncentate');
INSERT INTO `test` (`id`, `name`) VALUES (1097, 'Aparat za rezanje zelenjave');
INSERT INTO `test` (`id`, `name`) VALUES (3559, 'APARAT ZA REZANJE ZELENJAVE ');
INSERT INTO `test` (`id`, `name`) VALUES (294, 'Aparat za smetano');
INSERT INTO `test` (`id`, `name`) VALUES (3089, 'Aparat za tekoči sladoled');
INSERT INTO `test` (`id`, `name`) VALUES (985, 'Apropo - blagajniško poslovanje');
INSERT INTO `test` (`id`, `name`) VALUES (7512, 'ARAŠIDI 30G ROYAL S');
INSERT INTO `test` (`id`, `name`) VALUES (8560, 'ARAŠIDI BAHLSEN 100G');
INSERT INTO `test` (`id`, `name`) VALUES (10541, 'Arašidi Bahlsen vreč 0.1kg');
INSERT INTO `test` (`id`, `name`) VALUES (16638, 'Arašidi Bahlsen vreč 0.1kg');
INSERT INTO `test` (`id`, `name`) VALUES (9945, 'ARAŠIDI CELI 500 G MERCATOR');
INSERT INTO `test` (`id`, `name`) VALUES (9028, 'ARAŠIDI KELLY SLANI PRAŽENI 125G');
INSERT INTO `test` (`id`, `name`) VALUES (8738, 'ARAŠIDI M.NUT SL. 250G');
INSERT INTO `test` (`id`, `name`) VALUES (10542, 'Arašidi Mister Nut praženi slani vakum vreč 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (16639, 'Arašidi Mister Nut praženi slani vakum vreč 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (10543, 'Arašidi MisterNut vakum 0.25kg');
INSERT INTO `test` (`id`, `name`) VALUES (16640, 'Arašidi MisterNut vakum 0.25kg');
INSERT INTO `test` (`id`, `name`) VALUES (8739, 'ARAŠIDI MR.NUT VAKUM 500G ');
INSERT INTO `test` (`id`, `name`) VALUES (7511, 'ARAŠIDI PIKANT 150G ');
INSERT INTO `test` (`id`, `name`) VALUES (9983, 'ARAŠIDI PRAŽENI CELI MERCATOR 500G');
INSERT INTO `test` (`id`, `name`) VALUES (9923, 'ARAŠIDI PRAŽENI SLANI 200G MERCATOR');
INSERT INTO `test` (`id`, `name`) VALUES (10544, 'Arašidi praženi slani KZ Metlika vreč 1000 g');
INSERT INTO `test` (`id`, `name`) VALUES (16641, 'Arašidi praženi slani KZ Metlika vreč 1000 g');
INSERT INTO `test` (`id`, `name`) VALUES (10361, 'Arašidi praženi slani LBZ  KZ Metlika');
INSERT INTO `test` (`id`, `name`) VALUES (10545, 'Arašidi praženi slani Royal"s vreč 30g');
INSERT INTO `test` (`id`, `name`) VALUES (16642, 'Arašidi praženi slani Royal"s vreč 30g');
INSERT INTO `test` (`id`, `name`) VALUES (10546, 'Arašidi praženi v lupini vreč 0.5kg');
INSERT INTO `test` (`id`, `name`) VALUES (16643, 'Arašidi praženi v lupini vreč 0.5kg');
INSERT INTO `test` (`id`, `name`) VALUES (10547, 'Arašidi praženi v lupini vreč 5kg');
INSERT INTO `test` (`id`, `name`) VALUES (16644, 'Arašidi praženi v lupini vreč 5kg');
INSERT INTO `test` (`id`, `name`) VALUES (8743, 'ARAŠIDI PRAŽENI VAK.P. 100G');
INSERT INTO `test` (`id`, `name`) VALUES (6868, 'ARAŠIDI S ČILIJEM 500G');
INSERT INTO `test` (`id`, `name`) VALUES (9029, 'ARAŠIDI SL. PR. KELLY 500G');
INSERT INTO `test` (`id`, `name`) VALUES (8822, 'ARAŠIDI SLANI FOX 100G');
INSERT INTO `test` (`id`, `name`) VALUES (10548, 'Arašidi slani oluščeni sun nut vreč 100 g');
INSERT INTO `test` (`id`, `name`) VALUES (16645, 'Arašidi slani oluščeni sun nut vreč 100 g');
INSERT INTO `test` (`id`, `name`) VALUES (7959, 'ARAŠIDI SLANI PRAŽENI 1KG TUŠ');
INSERT INTO `test` (`id`, `name`) VALUES (8745, 'ARAŠIDI SLANI PRAŽENI 60G');
INSERT INTO `test` (`id`, `name`) VALUES (7504, 'ARAŠIDI SLANI ROYALS 1000g');
INSERT INTO `test` (`id`, `name`) VALUES (7503, 'ARAŠIDI SLANI ROYALS 250 G');
INSERT INTO `test` (`id`, `name`) VALUES (8110, 'ARAŠIDI SLANI SUN NUTIS 100G');
INSERT INTO `test` (`id`, `name`) VALUES (8737, 'ARAŠIDI SLANI VAK.P. 1000G');
INSERT INTO `test` (`id`, `name`) VALUES (10549, 'Arašidi slani vreč 60g');
INSERT INTO `test` (`id`, `name`) VALUES (16646, 'Arašidi slani vreč 60g');
INSERT INTO `test` (`id`, `name`) VALUES (9030, 'ARAŠIDI SOLJENI  225G  KELLYS ');
INSERT INTO `test` (`id`, `name`) VALUES (8529, 'ARAŠIDI SOLJENI 500G ULTJE INTERSNACK');
INSERT INTO `test` (`id`, `name`) VALUES (8112, 'ARAŠIDI SUN NUTS SL. 250G');
INSERT INTO `test` (`id`, `name`) VALUES (7749, 'ARAŠIDI V ČOKOLADI 100G');
INSERT INTO `test` (`id`, `name`) VALUES (3215, 'Arašidi v lupini');
INSERT INTO `test` (`id`, `name`) VALUES (7275, 'ARAŠIDI V LUPINI 25 KG');
INSERT INTO `test` (`id`, `name`) VALUES (7506, 'ARAŠIDI V LUPINI 2KG');
INSERT INTO `test` (`id`, `name`) VALUES (8742, 'ARAŠIDI V LUPINI 350G');
INSERT INTO `test` (`id`, `name`) VALUES (7505, 'ARAŠIDI V LUPINI 500 G');
INSERT INTO `test` (`id`, `name`) VALUES (7502, 'ARAŠIDI V LUPINI 5KG');
INSERT INTO `test` (`id`, `name`) VALUES (7228, 'ARAŠIDI V LUPINI-REFUZA 1KG');
INSERT INTO `test` (`id`, `name`) VALUES (2908, 'Arhivsko vino 1959 - LJUTOMERČAN');
INSERT INTO `test` (`id`, `name`) VALUES (2909, 'Arhivsko vino 1960 - LJUTOMERČAN');
INSERT INTO `test` (`id`, `name`) VALUES (2907, 'Arhivsko vino 1969 - LJUTOMERČAN');
INSERT INTO `test` (`id`, `name`) VALUES (2906, 'Arhivsko vino 1970 - LJUTOMERČAN');
INSERT INTO `test` (`id`, `name`) VALUES (15228, 'Aroma jagoda Etol UP koz 10ml');
INSERT INTO `test` (`id`, `name`) VALUES (21325, 'Aroma jagoda Etol UP koz 10ml');
INSERT INTO `test` (`id`, `name`) VALUES (15229, 'Aroma malina Etol UP koz 10g');
INSERT INTO `test` (`id`, `name`) VALUES (21326, 'Aroma malina Etol UP koz 10g');
INSERT INTO `test` (`id`, `name`) VALUES (8221, 'AROMA NARAVNA ZA ŽIVILA BANANA 10G');
INSERT INTO `test` (`id`, `name`) VALUES (8219, 'AROMA NARAVNA ZA ŽIVILA HRUŠKA 10G');
INSERT INTO `test` (`id`, `name`) VALUES (8220, 'AROMA NARAVNA ZA ŽIVILA MALINA 10G');
INSERT INTO `test` (`id`, `name`) VALUES (8218, 'AROMA NARAVNA ZA ŽIVILA META 10G');
INSERT INTO `test` (`id`, `name`) VALUES (8217, 'AROMA NARAVNA ZA ŽIVILA VIŠNJA 10G');
INSERT INTO `test` (`id`, `name`) VALUES (15230, 'Aroma rum etol koz. 10ml');
INSERT INTO `test` (`id`, `name`) VALUES (21327, 'Aroma rum etol koz. 10ml');
INSERT INTO `test` (`id`, `name`) VALUES (15231, 'Aroma vanilija Etol 10ml');
INSERT INTO `test` (`id`, `name`) VALUES (21328, 'Aroma vanilija Etol 10ml');
INSERT INTO `test` (`id`, `name`) VALUES (2997, 'Aromatična ekstra deviška olivna olja');
INSERT INTO `test` (`id`, `name`) VALUES (3576, 'ART SPRITZ 11% 1L BAUER');
INSERT INTO `test` (`id`, `name`) VALUES (8840, 'ARTIČOKE 2600 G');
INSERT INTO `test` (`id`, `name`) VALUES (7286, 'ARTIČOKE ALTIDORO 400G');
INSERT INTO `test` (`id`, `name`) VALUES (8521, 'ARTIČOKE CELE PARAMONGA 2650G ');
INSERT INTO `test` (`id`, `name`) VALUES (8856, 'ARTIČOKE PIZZA MAZZA 2500G DOZA');
INSERT INTO `test` (`id`, `name`) VALUES (10550, 'Artičoke rezane v sončn. olju Demetra vreč. 1.7kg');
INSERT INTO `test` (`id`, `name`) VALUES (16647, 'Artičoke rezane v sončn. olju Demetra vreč. 1.7kg');
INSERT INTO `test` (`id`, `name`) VALUES (10551, 'Artičoke rustici v sončn.olju Demetra ploč. 0.74kg');
INSERT INTO `test` (`id`, `name`) VALUES (16648, 'Artičoke rustici v sončn.olju Demetra ploč. 0.74kg');
INSERT INTO `test` (`id`, `name`) VALUES (10552, 'Artičoke s pecljem v sončn. olju Demetra ploč.770g');
INSERT INTO `test` (`id`, `name`) VALUES (16649, 'Artičoke s pecljem v sončn. olju Demetra ploč.770g');
INSERT INTO `test` (`id`, `name`) VALUES (10553, 'Artičoke srca Halcon Špan. ploč 0.39kg');
INSERT INTO `test` (`id`, `name`) VALUES (16650, 'Artičoke srca Halcon Špan. ploč 0.39kg');
INSERT INTO `test` (`id`, `name`) VALUES (10554, 'Artičoke srca Lena ploč 390g (neto plod 240g)');
INSERT INTO `test` (`id`, `name`) VALUES (16651, 'Artičoke srca Lena ploč 390g (neto plod 240g)');
INSERT INTO `test` (`id`, `name`) VALUES (10555, 'Artičoke srca Mediteraneas ploč. 2.65[1.35]kg');
INSERT INTO `test` (`id`, `name`) VALUES (16652, 'Artičoke srca Mediteraneas ploč. 2.65[1.35]kg');
INSERT INTO `test` (`id`, `name`) VALUES (10556, 'Artičoke srca v last.soku Delizie ploč 2.6 (1.2)kg');
INSERT INTO `test` (`id`, `name`) VALUES (16653, 'Artičoke srca v last.soku Delizie ploč 2.6 (1.2)kg');
INSERT INTO `test` (`id`, `name`) VALUES (6916, 'ARTIČOKE SRČKI BELLA ROSA 3KG PLOČ. (1360)');
INSERT INTO `test` (`id`, `name`) VALUES (8766, 'ARTIČOKE SRČKI MEDITERANEAS 3 KG PLOČ.');
INSERT INTO `test` (`id`, `name`) VALUES (6888, 'ARTIČOKE SRČKI NERI 3 KG PLOČ. (2.6KG)');
INSERT INTO `test` (`id`, `name`) VALUES (3003, 'Artičoke v ekstra deviškem olivnem olju');
INSERT INTO `test` (`id`, `name`) VALUES (7549, 'ARTIČOKE V KISU ETA 290G');
INSERT INTO `test` (`id`, `name`) VALUES (10557, 'Artičoke v strokih za pizzo Demetra vreč. 1.7kg');
INSERT INTO `test` (`id`, `name`) VALUES (16654, 'Artičoke v strokih za pizzo Demetra vreč. 1.7kg');
INSERT INTO `test` (`id`, `name`) VALUES (10558, 'Avokado svež 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (16655, 'Avokado svež 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (3393, 'Avto simulator');
INSERT INTO `test` (`id`, `name`) VALUES (324, 'Avtomatski podajalnik Tork Matic');
INSERT INTO `test` (`id`, `name`) VALUES (330, 'Avtomatsko senzorski podajalnik brisač-Aluminij TORK');
INSERT INTO `test` (`id`, `name`) VALUES (499, 'Baileys');
INSERT INTO `test` (`id`, `name`) VALUES (853, 'Bakla  falo ');
INSERT INTO `test` (`id`, `name`) VALUES (240, 'Ballantine\'s ');
INSERT INTO `test` (`id`, `name`) VALUES (8763, 'BALZAMIČNI KIS MONARI 1 L');
INSERT INTO `test` (`id`, `name`) VALUES (10559, 'Bambusovi vršički Shan\'shi ploč 0.3[0.17]kg');
INSERT INTO `test` (`id`, `name`) VALUES (16656, 'Bambusovi vršički Shan\'shi ploč 0.3[0.17]kg');
INSERT INTO `test` (`id`, `name`) VALUES (7095, 'BANANE');
INSERT INTO `test` (`id`, `name`) VALUES (10560, 'Banane sveže 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (16657, 'Banane sveže 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (455, 'Bar 2000');
INSERT INTO `test` (`id`, `name`) VALUES (10072, 'BAR 2000 - DOLCE');
INSERT INTO `test` (`id`, `name`) VALUES (10070, 'BAR 2000 - EXTRA');
INSERT INTO `test` (`id`, `name`) VALUES (10073, 'BAR 2000 - kavne blazinice EXTRA');
INSERT INTO `test` (`id`, `name`) VALUES (10074, 'BAR 2000 - kavne blazinice PROFUMATO');
INSERT INTO `test` (`id`, `name`) VALUES (10071, 'BAR 2000 - PROFUMATO');
INSERT INTO `test` (`id`, `name`) VALUES (10363, 'Bar FEŠTA');
INSERT INTO `test` (`id`, `name`) VALUES (2487, 'Barbara - ISTENIc');
INSERT INTO `test` (`id`, `name`) VALUES (256, 'Barbera');
INSERT INTO `test` (`id`, `name`) VALUES (2483, 'Barbera - IPAVEC ROMAN');
INSERT INTO `test` (`id`, `name`) VALUES (2626, 'Barbera - LISJAK RADIVOJ');
INSERT INTO `test` (`id`, `name`) VALUES (2636, 'Barbera rose - MAKOVEC');
INSERT INTO `test` (`id`, `name`) VALUES (456, 'Barcaffé Bar');
INSERT INTO `test` (`id`, `name`) VALUES (457, 'Barcaffé Bar Espresso');
INSERT INTO `test` (`id`, `name`) VALUES (458, 'Barcaffé Bar Prestige');
INSERT INTO `test` (`id`, `name`) VALUES (459, 'Barcaffé Dekofe Espresso');
INSERT INTO `test` (`id`, `name`) VALUES (8867, 'BARILLA ŠPAGETI NAJTANŠI  500g ');
INSERT INTO `test` (`id`, `name`) VALUES (1009, 'Barman izobraževanja');
INSERT INTO `test` (`id`, `name`) VALUES (1011, 'Barmenski tečaji');
INSERT INTO `test` (`id`, `name`) VALUES (1008, 'Barski catering');
INSERT INTO `test` (`id`, `name`) VALUES (1013, 'Barski catering');
INSERT INTO `test` (`id`, `name`) VALUES (2965, 'Barski stol Antony');
INSERT INTO `test` (`id`, `name`) VALUES (3013, 'Barski stol Beta');
INSERT INTO `test` (`id`, `name`) VALUES (3106, 'barski stol CREO  3173');
INSERT INTO `test` (`id`, `name`) VALUES (3110, 'barski stol CREO  3313');
INSERT INTO `test` (`id`, `name`) VALUES (3014, 'Barski stol Miriana');
INSERT INTO `test` (`id`, `name`) VALUES (5099, 'Barski stol WEZ');
INSERT INTO `test` (`id`, `name`) VALUES (10068, 'Barski stoli');
INSERT INTO `test` (`id`, `name`) VALUES (3011, 'Barski stoli - Teza');
INSERT INTO `test` (`id`, `name`) VALUES (3012, 'Barski stoli - Tone bar');
INSERT INTO `test` (`id`, `name`) VALUES (3015, 'Barski stoli -Antonio');
INSERT INTO `test` (`id`, `name`) VALUES (15232, 'Barvilo za živila jagodno rdeča Žito pet. 0.250kg');
INSERT INTO `test` (`id`, `name`) VALUES (21329, 'Barvilo za živila jagodno rdeča Žito pet. 0.250kg');
INSERT INTO `test` (`id`, `name`) VALUES (15371, 'Baterija alkalna Maxell 1.5V LR20 D zavit 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (21468, 'Baterija alkalna Maxell 1.5V LR20 D zavit 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (15372, 'Baterija alkalna Maxell 9V LF22 zavit 1kos');
INSERT INTO `test` (`id`, `name`) VALUES (21469, 'Baterija alkalna Maxell 9V LF22 zavit 1kos');
INSERT INTO `test` (`id`, `name`) VALUES (15373, 'Baterija alkalna Maxell AA 1.5V LR6 zavit 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (21470, 'Baterija alkalna Maxell AA 1.5V LR6 zavit 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (15374, 'Baterija alkalna Maxell AA 1.5V LR6 zavit 4kos');
INSERT INTO `test` (`id`, `name`) VALUES (21471, 'Baterija alkalna Maxell AA 1.5V LR6 zavit 4kos');
INSERT INTO `test` (`id`, `name`) VALUES (15375, 'Baterija alkalna Maxell AAA 1.5V  zavit 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (21472, 'Baterija alkalna Maxell AAA 1.5V  zavit 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (15376, 'Baterija alkalna Maxell C 1.5V LR14 zavit 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (21473, 'Baterija alkalna Maxell C 1.5V LR14 zavit 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (15377, 'Baterija alkalna sup Maxell AA 1.5V LR6 zavit 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (21474, 'Baterija alkalna sup Maxell AA 1.5V LR6 zavit 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (15378, 'Baterija Maxell 1.5V LR20 D zavit 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (21475, 'Baterija Maxell 1.5V LR20 D zavit 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (15379, 'Baterija Maxell C 1.5V R14 zavit 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (21476, 'Baterija Maxell C 1.5V R14 zavit 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (15380, 'Baterija s-alkalna Maxell C 1.5V LR03 zavit 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (21477, 'Baterija s-alkalna Maxell C 1.5V LR03 zavit 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (15381, 'Baterija Univer-cel 4.5V LR3 zavit 1kom');
INSERT INTO `test` (`id`, `name`) VALUES (21478, 'Baterija Univer-cel 4.5V LR3 zavit 1kom');
INSERT INTO `test` (`id`, `name`) VALUES (10561, 'Bazilika drobljena Droga UP koz 14g');
INSERT INTO `test` (`id`, `name`) VALUES (16658, 'Bazilika drobljena Droga UP koz 14g');
INSERT INTO `test` (`id`, `name`) VALUES (10562, 'Bazilika drobljena Kotanyi koz 15g');
INSERT INTO `test` (`id`, `name`) VALUES (16659, 'Bazilika drobljena Kotanyi koz 15g');
INSERT INTO `test` (`id`, `name`) VALUES (10563, 'Bazilika drobljena Kotanyi pet 162g');
INSERT INTO `test` (`id`, `name`) VALUES (16660, 'Bazilika drobljena Kotanyi pet 162g');
INSERT INTO `test` (`id`, `name`) VALUES (10564, 'Bazilika drobljena Kotanyi vreč 9g');
INSERT INTO `test` (`id`, `name`) VALUES (16661, 'Bazilika drobljena Kotanyi vreč 9g');
INSERT INTO `test` (`id`, `name`) VALUES (2444, 'Beaujolais Revelation - DOMAINE RUET');
INSERT INTO `test` (`id`, `name`) VALUES (2445, 'Beaujolais Rose - DOMAINE RUET');
INSERT INTO `test` (`id`, `name`) VALUES (243, 'Beck\'s');
INSERT INTO `test` (`id`, `name`) VALUES (10565, 'Bedra piščančja bk');
INSERT INTO `test` (`id`, `name`) VALUES (16662, 'Bedra piščančja bk');
INSERT INTO `test` (`id`, `name`) VALUES (10566, 'Bedra piščančja nekalibrirana');
INSERT INTO `test` (`id`, `name`) VALUES (16663, 'Bedra piščančja nekalibrirana');
INSERT INTO `test` (`id`, `name`) VALUES (2949, 'Bela sladkorna masa  Massa bianca');
INSERT INTO `test` (`id`, `name`) VALUES (7917, 'BELA ŠTRUCA R-20 T-500 1KG');
INSERT INTO `test` (`id`, `name`) VALUES (2517, 'Beli pinot - JERUZALEM - ORMOZ');
INSERT INTO `test` (`id`, `name`) VALUES (2525, 'Beli pinot - KABAJ');
INSERT INTO `test` (`id`, `name`) VALUES (2593, 'Beli pinot - KRISTANCIC DUSAN');
INSERT INTO `test` (`id`, `name`) VALUES (2627, 'Beli pinot - LISJAK RADIVOJ');
INSERT INTO `test` (`id`, `name`) VALUES (2903, 'Beli pinot - RONK');
INSERT INTO `test` (`id`, `name`) VALUES (2763, 'Beli pinot - SCUREK');
INSERT INTO `test` (`id`, `name`) VALUES (2780, 'Beli pinot - SIMCIC EDI');
INSERT INTO `test` (`id`, `name`) VALUES (2549, 'Beli pinot 0.20 Quercus - GORIsKA BRDA');
INSERT INTO `test` (`id`, `name`) VALUES (2550, 'Beli pinot Quercus - GORIsKA BRDA');
INSERT INTO `test` (`id`, `name`) VALUES (2901, 'Beli pinot-ZLATI GRIc');
INSERT INTO `test` (`id`, `name`) VALUES (435, 'Beli program LM');
INSERT INTO `test` (`id`, `name`) VALUES (2397, 'Bellavista Franciacorta Cuvee - BELLAVISTA');
INSERT INTO `test` (`id`, `name`) VALUES (2395, 'Bellavista Franciacorta Gran Cuvee Rose - BELLAVISTA');
INSERT INTO `test` (`id`, `name`) VALUES (2396, 'Bellavista Franciacorta Gran Cuvee Saten - BELLAVISTA');
INSERT INTO `test` (`id`, `name`) VALUES (8184, 'BELUŠI 330 G ');
INSERT INTO `test` (`id`, `name`) VALUES (8523, 'BELUŠI BELI 460 MLL');
INSERT INTO `test` (`id`, `name`) VALUES (10567, 'Beluši beli olupljeni b.konz. Eta koz. 0.33[0.20');
INSERT INTO `test` (`id`, `name`) VALUES (16664, 'Beluši beli olupljeni b.konz. Eta koz. 0.33[0.20');
INSERT INTO `test` (`id`, `name`) VALUES (10568, 'Beluši beli olupljeni every day koz.0.33g');
INSERT INTO `test` (`id`, `name`) VALUES (16665, 'Beluši beli olupljeni every day koz.0.33g');
INSERT INTO `test` (`id`, `name`) VALUES (10569, 'Beluši beli olupljeni Iska koz. 660g');
INSERT INTO `test` (`id`, `name`) VALUES (16666, 'Beluši beli olupljeni Iska koz. 660g');
INSERT INTO `test` (`id`, `name`) VALUES (6952, 'BELUŠI BELI TRAMONTE 370 G KOZ.');
INSERT INTO `test` (`id`, `name`) VALUES (10570, 'Beluši zeleni');
INSERT INTO `test` (`id`, `name`) VALUES (16667, 'Beluši zeleni');
INSERT INTO `test` (`id`, `name`) VALUES (6512, 'BELUŠI ZELENI CELI 1KG ZM');
INSERT INTO `test` (`id`, `name`) VALUES (10571, 'Beluši zeleni Lutece Nz. koz. 0.33[0.185]kg');
INSERT INTO `test` (`id`, `name`) VALUES (16668, 'Beluši zeleni Lutece Nz. koz. 0.33[0.185]kg');
INSERT INTO `test` (`id`, `name`) VALUES (10572, 'Beluši zeleni sveži 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (16669, 'Beluši zeleni sveži 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (6953, 'BELUŠI ZELENI TRAMONTE 370G KOZ.');
INSERT INTO `test` (`id`, `name`) VALUES (8980, 'BELUŠI ZELENI V SLANICI 370 ML LUTECE');
INSERT INTO `test` (`id`, `name`) VALUES (10096, 'Beluši zeleni zamrznjeni ');
INSERT INTO `test` (`id`, `name`) VALUES (10573, 'Beluši zeleni zamrznjeni vreč 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (16670, 'Beluši zeleni zamrznjeni vreč 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (9616, 'BENQUICK KROGLICE CHOCO.  1KG');
INSERT INTO `test` (`id`, `name`) VALUES (3492, 'Best music on line');
INSERT INTO `test` (`id`, `name`) VALUES (5438, 'BIBITA LEMON LIGHT 2L');
INSERT INTO `test` (`id`, `name`) VALUES (5437, 'BIBITA ORANGE LIGHT 2L PVC');
INSERT INTO `test` (`id`, `name`) VALUES (2952, 'Biljard');
INSERT INTO `test` (`id`, `name`) VALUES (15233, 'Biokill Insekticid univ. proto mrčesu razpr.0.5L');
INSERT INTO `test` (`id`, `name`) VALUES (21330, 'Biokill Insekticid univ. proto mrčesu razpr.0.5L');
INSERT INTO `test` (`id`, `name`) VALUES (608, 'Birokrat POS Gostinec');
INSERT INTO `test` (`id`, `name`) VALUES (3432, 'Birokrat POS Trgovec');
INSERT INTO `test` (`id`, `name`) VALUES (233, 'BISHE jagode&vino');
INSERT INTO `test` (`id`, `name`) VALUES (2945, 'Biskvit mix z jajci');
INSERT INTO `test` (`id`, `name`) VALUES (8587, 'BISKVIT RESANA ORANGE 125G');
INSERT INTO `test` (`id`, `name`) VALUES (10574, 'Biskvit s penastim polnilom Munchmallow škat 105g');
INSERT INTO `test` (`id`, `name`) VALUES (16671, 'Biskvit s penastim polnilom Munchmallow škat 105g');
INSERT INTO `test` (`id`, `name`) VALUES (10575, 'Biskvit za torto kakav  zavit 0.4kg');
INSERT INTO `test` (`id`, `name`) VALUES (16672, 'Biskvit za torto kakav  zavit 0.4kg');
INSERT INTO `test` (`id`, `name`) VALUES (10576, 'Biskvit za torto vanilija Dahlhoff zavit 0.4kg');
INSERT INTO `test` (`id`, `name`) VALUES (16673, 'Biskvit za torto vanilija Dahlhoff zavit 0.4kg');
INSERT INTO `test` (`id`, `name`) VALUES (10577, 'Bitter istra IstraVinoExport (24%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (16674, 'Bitter istra IstraVinoExport (24%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (2404, 'Bjana Brut - BJANA');
INSERT INTO `test` (`id`, `name`) VALUES (2405, 'Bjana Rose - BJANA');
INSERT INTO `test` (`id`, `name`) VALUES (3595, 'BLACK MAGIC 1L 23% BAUER');
INSERT INTO `test` (`id`, `name`) VALUES (3594, 'BLACK MAGIC 2L 23% BAUER');
INSERT INTO `test` (`id`, `name`) VALUES (155, 'Blagajna GIS Prestige gostinstvo');
INSERT INTO `test` (`id`, `name`) VALUES (950, 'Blagajna Relax Prestige ');
INSERT INTO `test` (`id`, `name`) VALUES (949, 'Blagajna TS Prestige storitvene dejavnosti');
INSERT INTO `test` (`id`, `name`) VALUES (948, 'Blagajna TS Prestige trgovine');
INSERT INTO `test` (`id`, `name`) VALUES (955, 'Blagajna WIN Go gostinstvo ');
INSERT INTO `test` (`id`, `name`) VALUES (986, 'Blagajne all in one');
INSERT INTO `test` (`id`, `name`) VALUES (2895, 'Blatina - VINARIJA cITLUK');
INSERT INTO `test` (`id`, `name`) VALUES (2406, 'Blaz rdece - BLAzIc');
INSERT INTO `test` (`id`, `name`) VALUES (3482, 'Blazina za stol');
INSERT INTO `test` (`id`, `name`) VALUES (3257, 'Blender ARISTARCO STAR 1');
INSERT INTO `test` (`id`, `name`) VALUES (10578, 'Blitva');
INSERT INTO `test` (`id`, `name`) VALUES (16675, 'Blitva');
INSERT INTO `test` (`id`, `name`) VALUES (10097, 'Blitva zamrznjena ');
INSERT INTO `test` (`id`, `name`) VALUES (10579, 'Blitva zamrznjena vreč 2.5kg');
INSERT INTO `test` (`id`, `name`) VALUES (16676, 'Blitva zamrznjena vreč 2.5kg');
INSERT INTO `test` (`id`, `name`) VALUES (1100, 'Blixer - Cutter in mikser v enem');
INSERT INTO `test` (`id`, `name`) VALUES (10304, 'Bolhe');
INSERT INTO `test` (`id`, `name`) VALUES (497, 'Bombay Sapphire Gin.');
INSERT INTO `test` (`id`, `name`) VALUES (10580, 'Bombice za smetano Euro.+Liss škat. 50kos');
INSERT INTO `test` (`id`, `name`) VALUES (16677, 'Bombice za smetano Euro.+Liss škat. 50kos');
INSERT INTO `test` (`id`, `name`) VALUES (10581, 'Bombice za smetano Evro.+Liss škat. 10kom');
INSERT INTO `test` (`id`, `name`) VALUES (16678, 'Bombice za smetano Evro.+Liss škat. 10kom');
INSERT INTO `test` (`id`, `name`) VALUES (10582, 'Bombice za smetano N2O-24 Liss škat. 24kos');
INSERT INTO `test` (`id`, `name`) VALUES (16679, 'Bombice za smetano N2O-24 Liss škat. 24kos');
INSERT INTO `test` (`id`, `name`) VALUES (293, 'Bombice za smetano.');
INSERT INTO `test` (`id`, `name`) VALUES (10583, 'Bonboni 505 s črto 100g+25% gratis');
INSERT INTO `test` (`id`, `name`) VALUES (16680, 'Bonboni 505 s črto 100g+25% gratis');
INSERT INTO `test` (`id`, `name`) VALUES (10584, 'Bonboni Bronhi Kraš vreč 0.2kg');
INSERT INTO `test` (`id`, `name`) VALUES (16681, 'Bonboni Bronhi Kraš vreč 0.2kg');
INSERT INTO `test` (`id`, `name`) VALUES (10585, 'Bonboni Bronhi orginal karamela Kraš vreč 100g');
INSERT INTO `test` (`id`, `name`) VALUES (16682, 'Bonboni Bronhi orginal karamela Kraš vreč 100g');
INSERT INTO `test` (`id`, `name`) VALUES (10586, 'Bonboni Casali rum kokos škat 0.3kg');
INSERT INTO `test` (`id`, `name`) VALUES (16683, 'Bonboni Casali rum kokos škat 0.3kg');
INSERT INTO `test` (`id`, `name`) VALUES (10587, 'Bonboni Casali rum kokos vreč 0.1kg');
INSERT INTO `test` (`id`, `name`) VALUES (16684, 'Bonboni Casali rum kokos vreč 0.1kg');
INSERT INTO `test` (`id`, `name`) VALUES (10588, 'Bonboni Cedevita limona zavit 20g');
INSERT INTO `test` (`id`, `name`) VALUES (16685, 'Bonboni Cedevita limona zavit 20g');
INSERT INTO `test` (`id`, `name`) VALUES (10589, 'Bonboni Cedevita pomaranča zavit 19.5g');
INSERT INTO `test` (`id`, `name`) VALUES (16686, 'Bonboni Cedevita pomaranča zavit 19.5g');
INSERT INTO `test` (`id`, `name`) VALUES (10591, 'Bonboni čokoladni draže Kraš škat 350g');
INSERT INTO `test` (`id`, `name`) VALUES (16688, 'Bonboni čokoladni draže Kraš škat 350g');
INSERT INTO `test` (`id`, `name`) VALUES (10592, 'Bonboni čokoladni Rovelli mix vreč. 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (16689, 'Bonboni čokoladni Rovelli mix vreč. 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (10593, 'Bonboni čokoladni s krispiji (400 kos) škat 440g');
INSERT INTO `test` (`id`, `name`) VALUES (16690, 'Bonboni čokoladni s krispiji (400 kos) škat 440g');
INSERT INTO `test` (`id`, `name`) VALUES (10590, 'Bonboni Cola frizzy trdi Liking vreč 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (16687, 'Bonboni Cola frizzy trdi Liking vreč 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (10594, 'Bonboni Eukalipta Žito vreč 90g');
INSERT INTO `test` (`id`, `name`) VALUES (16691, 'Bonboni Eukalipta Žito vreč 90g');
INSERT INTO `test` (`id`, `name`) VALUES (10595, 'Bonboni Fru Fru Multivitamin Šumi vreč. 100g');
INSERT INTO `test` (`id`, `name`) VALUES (16692, 'Bonboni Fru Fru Multivitamin Šumi vreč. 100g');
INSERT INTO `test` (`id`, `name`) VALUES (10596, 'Bonboni FruFru Šumi vreč 0.4kg');
INSERT INTO `test` (`id`, `name`) VALUES (16693, 'Bonboni FruFru Šumi vreč 0.4kg');
INSERT INTO `test` (`id`, `name`) VALUES (10597, 'Bonboni gumi  Park lane burger vreč 100 g');
INSERT INTO `test` (`id`, `name`) VALUES (16694, 'Bonboni gumi  Park lane burger vreč 100 g');
INSERT INTO `test` (`id`, `name`) VALUES (10598, 'Bonboni gumi Draculas Park lane vreč.100g');
INSERT INTO `test` (`id`, `name`) VALUES (16695, 'Bonboni gumi Draculas Park lane vreč.100g');
INSERT INTO `test` (`id`, `name`) VALUES (10599, 'Bonboni gumi haribo sadni robida vreč 100g');
INSERT INTO `test` (`id`, `name`) VALUES (16696, 'Bonboni gumi haribo sadni robida vreč 100g');
INSERT INTO `test` (`id`, `name`) VALUES (10600, 'Bonboni gumi lobenje vreč 100 g');
INSERT INTO `test` (`id`, `name`) VALUES (16697, 'Bonboni gumi lobenje vreč 100 g');
INSERT INTO `test` (`id`, `name`) VALUES (10601, 'Bonboni gumi obročki vreč 100 g');
INSERT INTO `test` (`id`, `name`) VALUES (16698, 'Bonboni gumi obročki vreč 100 g');
INSERT INTO `test` (`id`, `name`) VALUES (10602, 'Bonboni karamele mešane Kandit vreč 400g');
INSERT INTO `test` (`id`, `name`) VALUES (16699, 'Bonboni karamele mešane Kandit vreč 400g');
INSERT INTO `test` (`id`, `name`) VALUES (10603, 'Bonboni kavni z mleč.kremo Interv. 270kos vreč 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (16700, 'Bonboni kavni z mleč.kremo Interv. 270kos vreč 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (10604, 'Bonboni Kavno zrno oblito s čok.(400 kos) škat 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (16701, 'Bonboni Kavno zrno oblito s čok.(400 kos) škat 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (10605, 'Bonboni Kiki Kraš vreč 100g');
INSERT INTO `test` (`id`, `name`) VALUES (16702, 'Bonboni Kiki Kraš vreč 100g');
INSERT INTO `test` (`id`, `name`) VALUES (10606, 'Bonboni kisle gliste PL vreč 100 g');
INSERT INTO `test` (`id`, `name`) VALUES (16703, 'Bonboni kisle gliste PL vreč 100 g');
INSERT INTO `test` (`id`, `name`) VALUES (10607, 'Bonboni M & M choco peanut vreč 48g');
INSERT INTO `test` (`id`, `name`) VALUES (16704, 'Bonboni M & M choco peanut vreč 48g');
INSERT INTO `test` (`id`, `name`) VALUES (10608, 'Bonboni Mandelj s kaka.prelivom (400kos) škat 900g');
INSERT INTO `test` (`id`, `name`) VALUES (16705, 'Bonboni Mandelj s kaka.prelivom (400kos) škat 900g');
INSERT INTO `test` (`id`, `name`) VALUES (10609, 'Bonboni Menta MiniClub trdi Sperlari vreč 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (16706, 'Bonboni Menta MiniClub trdi Sperlari vreč 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (10610, 'Bonboni Misto creme trdi z lešnik kremo vreč 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (16707, 'Bonboni Misto creme trdi z lešnik kremo vreč 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (10611, 'Bonboni multi vitamin Piasten vreč 400g');
INSERT INTO `test` (`id`, `name`) VALUES (16708, 'Bonboni multi vitamin Piasten vreč 400g');
INSERT INTO `test` (`id`, `name`) VALUES (10612, 'Bonboni Negro Pionir vreč. 100g');
INSERT INTO `test` (`id`, `name`) VALUES (16709, 'Bonboni Negro Pionir vreč. 100g');
INSERT INTO `test` (`id`, `name`) VALUES (10613, 'Bonboni Orbit Delight meta s čokol. škat. 35g');
INSERT INTO `test` (`id`, `name`) VALUES (16710, 'Bonboni Orbit Delight meta s čokol. škat. 35g');
INSERT INTO `test` (`id`, `name`) VALUES (10614, 'Bonboni Pepermint Kraš vreč 100g');
INSERT INTO `test` (`id`, `name`) VALUES (16711, 'Bonboni Pepermint Kraš vreč 100g');
INSERT INTO `test` (`id`, `name`) VALUES (10615, 'Bonboni Pez sor. Kolinska zavit 8.5g');
INSERT INTO `test` (`id`, `name`) VALUES (16712, 'Bonboni Pez sor. Kolinska zavit 8.5g');
INSERT INTO `test` (`id`, `name`) VALUES (10616, 'Bonboni Pocket coffe škat 62.5 g');
INSERT INTO `test` (`id`, `name`) VALUES (16713, 'Bonboni Pocket coffe škat 62.5 g');
INSERT INTO `test` (`id`, `name`) VALUES (10617, 'Bonboni polnjeni trdi mešani Kandit vreč 400g');
INSERT INTO `test` (`id`, `name`) VALUES (16714, 'Bonboni polnjeni trdi mešani Kandit vreč 400g');
INSERT INTO `test` (`id`, `name`) VALUES (10618, 'Bonboni Ricola Salbei 75g');
INSERT INTO `test` (`id`, `name`) VALUES (16715, 'Bonboni Ricola Salbei 75g');
INSERT INTO `test` (`id`, `name`) VALUES (10619, 'Bonboni Ricola zeliščni brez slad. UP vreč 50g');
INSERT INTO `test` (`id`, `name`) VALUES (16716, 'Bonboni Ricola zeliščni brez slad. UP vreč 50g');
INSERT INTO `test` (`id`, `name`) VALUES (10620, 'Bonboni Rovelli s kapučino kremo. žitarice vreč.1k');
INSERT INTO `test` (`id`, `name`) VALUES (16717, 'Bonboni Rovelli s kapučino kremo. žitarice vreč.1k');
INSERT INTO `test` (`id`, `name`) VALUES (10621, 'Bonboni Rovelli s kokosovo kremo. žitarice vreč.1k');
INSERT INTO `test` (`id`, `name`) VALUES (16718, 'Bonboni Rovelli s kokosovo kremo. žitarice vreč.1k');
INSERT INTO `test` (`id`, `name`) VALUES (10622, 'Bonboni Rovelli z belo mlečno kremo.žita. vreč. 1k');
INSERT INTO `test` (`id`, `name`) VALUES (16719, 'Bonboni Rovelli z belo mlečno kremo.žita. vreč. 1k');
INSERT INTO `test` (`id`, `name`) VALUES (10623, 'Bonboni sadni Caramelline trdi Sperlari vreč 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (16720, 'Bonboni sadni Caramelline trdi Sperlari vreč 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (10624, 'Bonboni sadni Gu-gu Mlinotest vreč 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (16721, 'Bonboni sadni Gu-gu Mlinotest vreč 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (10625, 'Bonboni sadni Gugu Mlinotest vreč 250g');
INSERT INTO `test` (`id`, `name`) VALUES (16722, 'Bonboni sadni Gugu Mlinotest vreč 250g');
INSERT INTO `test` (`id`, `name`) VALUES (10626, 'Bonboni sadni Softi Hitschler vreč 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (16723, 'Bonboni sadni Softi Hitschler vreč 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (10627, 'Bonboni sadni Spicchi Ripieni trdi vreč 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (16724, 'Bonboni sadni Spicchi Ripieni trdi vreč 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (10628, 'Bonboni sadni Šumi mix vreč 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (16725, 'Bonboni sadni Šumi mix vreč 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (10629, 'Bonboni sadni žele Katjes vreč 75 g');
INSERT INTO `test` (`id`, `name`) VALUES (16726, 'Bonboni sadni žele Katjes vreč 75 g');
INSERT INTO `test` (`id`, `name`) VALUES (10631, 'Bonboni Šššum jabolko Žito vreč 0.1kg');
INSERT INTO `test` (`id`, `name`) VALUES (16728, 'Bonboni Šššum jabolko Žito vreč 0.1kg');
INSERT INTO `test` (`id`, `name`) VALUES (10632, 'Bonboni Šššum zeleno jabolko UP vreč. 400g');
INSERT INTO `test` (`id`, `name`) VALUES (16729, 'Bonboni Šššum zeleno jabolko UP vreč. 400g');
INSERT INTO `test` (`id`, `name`) VALUES (10633, 'Bonboni švicarski mentol Žito vreč 100g');
INSERT INTO `test` (`id`, `name`) VALUES (16730, 'Bonboni švicarski mentol Žito vreč 100g');
INSERT INTO `test` (`id`, `name`) VALUES (10630, 'Bonboni svileni lešnik Žito vreč 100g');
INSERT INTO `test` (`id`, `name`) VALUES (16727, 'Bonboni svileni lešnik Žito vreč 100g');
INSERT INTO `test` (`id`, `name`) VALUES (10634, 'Bonboni Toffifee s karamelo in lešniki škat 0.125');
INSERT INTO `test` (`id`, `name`) VALUES (16731, 'Bonboni Toffifee s karamelo in lešniki škat 0.125');
INSERT INTO `test` (`id`, `name`) VALUES (10635, 'Bonboni trdi Tesori lešnik krema vreč 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (16732, 'Bonboni trdi Tesori lešnik krema vreč 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (10636, 'Bonboni visoki C Žito vreč 0.1kg');
INSERT INTO `test` (`id`, `name`) VALUES (16733, 'Bonboni visoki C Žito vreč 0.1kg');
INSERT INTO `test` (`id`, `name`) VALUES (10637, 'Bonboni Vitergin jagoda kom 24g');
INSERT INTO `test` (`id`, `name`) VALUES (16734, 'Bonboni Vitergin jagoda kom 24g');
INSERT INTO `test` (`id`, `name`) VALUES (10638, 'Bonboni Vitergin pomaranča kom 24g');
INSERT INTO `test` (`id`, `name`) VALUES (16735, 'Bonboni Vitergin pomaranča kom 24g');
INSERT INTO `test` (`id`, `name`) VALUES (10639, 'Bonboni Werthers Original vreč 90 g');
INSERT INTO `test` (`id`, `name`) VALUES (16736, 'Bonboni Werthers Original vreč 90 g');
INSERT INTO `test` (`id`, `name`) VALUES (10641, 'Bonboni žajbelj b.s. Matik zavit 75g');
INSERT INTO `test` (`id`, `name`) VALUES (16738, 'Bonboni žajbelj b.s. Matik zavit 75g');
INSERT INTO `test` (`id`, `name`) VALUES (10642, 'Bonboni žele sadni haribo vreč 100 g');
INSERT INTO `test` (`id`, `name`) VALUES (16739, 'Bonboni žele sadni haribo vreč 100 g');
INSERT INTO `test` (`id`, `name`) VALUES (10643, 'Bonboni žele sadni orkester Žito vreč 400g');
INSERT INTO `test` (`id`, `name`) VALUES (16740, 'Bonboni žele sadni orkester Žito vreč 400g');
INSERT INTO `test` (`id`, `name`) VALUES (10644, 'Bonboni žele sadni šumi vreč 350 g');
INSERT INTO `test` (`id`, `name`) VALUES (16741, 'Bonboni žele sadni šumi vreč 350 g');
INSERT INTO `test` (`id`, `name`) VALUES (10640, 'Bonboni zeliščni Broncn-0-plus škat 100g');
INSERT INTO `test` (`id`, `name`) VALUES (16737, 'Bonboni zeliščni Broncn-0-plus škat 100g');
INSERT INTO `test` (`id`, `name`) VALUES (10645, 'Bonboni žitarice s čo. oblivom Zaini vreč 1 kg');
INSERT INTO `test` (`id`, `name`) VALUES (16742, 'Bonboni žitarice s čo. oblivom Zaini vreč 1 kg');
INSERT INTO `test` (`id`, `name`) VALUES (10646, 'Bonboniera After eighr Nestle škat 0.2kg');
INSERT INTO `test` (`id`, `name`) VALUES (16743, 'Bonboniera After eighr Nestle škat 0.2kg');
INSERT INTO `test` (`id`, `name`) VALUES (10647, 'Bonboniera Atlantis Vitaminka škat. 200g');
INSERT INTO `test` (`id`, `name`) VALUES (16744, 'Bonboniera Atlantis Vitaminka škat. 200g');
INSERT INTO `test` (`id`, `name`) VALUES (10648, 'Bonboniera Bajadera Kraš škat 0.1kg');
INSERT INTO `test` (`id`, `name`) VALUES (16745, 'Bonboniera Bajadera Kraš škat 0.1kg');
INSERT INTO `test` (`id`, `name`) VALUES (10649, 'Bonboniera Bajadera Kraš škat 0.2kg');
INSERT INTO `test` (`id`, `name`) VALUES (16746, 'Bonboniera Bajadera Kraš škat 0.2kg');
INSERT INTO `test` (`id`, `name`) VALUES (10650, 'Bonboniera Bajadera Kraš škat 0.3kg');
INSERT INTO `test` (`id`, `name`) VALUES (16747, 'Bonboniera Bajadera Kraš škat 0.3kg');
INSERT INTO `test` (`id`, `name`) VALUES (10651, 'Bonboniera Bajadera Kraš škat 0.5 kg');
INSERT INTO `test` (`id`, `name`) VALUES (16748, 'Bonboniera Bajadera Kraš škat 0.5 kg');
INSERT INTO `test` (`id`, `name`) VALUES (10652, 'Bonboniera Bajadera Kraš škat 0.9kg');
INSERT INTO `test` (`id`, `name`) VALUES (16749, 'Bonboniera Bajadera Kraš škat 0.9kg');
INSERT INTO `test` (`id`, `name`) VALUES (10653, 'Bonboniera Bajadera Kraš škat 37g');
INSERT INTO `test` (`id`, `name`) VALUES (16750, 'Bonboniera Bajadera Kraš škat 37g');
INSERT INTO `test` (`id`, `name`) VALUES (10654, 'Bonboniera Baron praline škat. 195g');
INSERT INTO `test` (`id`, `name`) VALUES (16751, 'Bonboniera Baron praline škat. 195g');
INSERT INTO `test` (`id`, `name`) VALUES (10655, 'Bonboniera Fontana ledene kocke Kraš škat 0.295');
INSERT INTO `test` (`id`, `name`) VALUES (16752, 'Bonboniera Fontana ledene kocke Kraš škat 0.295');
INSERT INTO `test` (`id`, `name`) VALUES (10656, 'Bonboniera Fontana ledene kocke Kraš zavit 49g');
INSERT INTO `test` (`id`, `name`) VALUES (16753, 'Bonboniera Fontana ledene kocke Kraš zavit 49g');
INSERT INTO `test` (`id`, `name`) VALUES (10657, 'Bonboniera Fontana ledene kocke Kraš zavit 725g');
INSERT INTO `test` (`id`, `name`) VALUES (16754, 'Bonboniera Fontana ledene kocke Kraš zavit 725g');
INSERT INTO `test` (`id`, `name`) VALUES (10658, 'Bonboniera Griotte Kraš škat. 51g');
INSERT INTO `test` (`id`, `name`) VALUES (16755, 'Bonboniera Griotte Kraš škat. 51g');
INSERT INTO `test` (`id`, `name`) VALUES (10659, 'Bonboniera Griotte Kraš zavit 1.024kg');
INSERT INTO `test` (`id`, `name`) VALUES (16756, 'Bonboniera Griotte Kraš zavit 1.024kg');
INSERT INTO `test` (`id`, `name`) VALUES (10660, 'Bonboniera Rojal 200g');
INSERT INTO `test` (`id`, `name`) VALUES (16757, 'Bonboniera Rojal 200g');
INSERT INTO `test` (`id`, `name`) VALUES (10661, 'Bonboniera sestavljanka 120 g');
INSERT INTO `test` (`id`, `name`) VALUES (16758, 'Bonboniera sestavljanka 120 g');
INSERT INTO `test` (`id`, `name`) VALUES (2387, 'Bonisimus cuvee - BATIC');
INSERT INTO `test` (`id`, `name`) VALUES (5296, 'BOROVNICA SIRUP NEKTAR 5L');
INSERT INTO `test` (`id`, `name`) VALUES (6325, 'BOROVNICE 2.5KG LEDO ZM');
INSERT INTO `test` (`id`, `name`) VALUES (6507, 'BOROVNICE ZAMRZNJENE 2.5KG VREČ. LJUB.MLEK');
INSERT INTO `test` (`id`, `name`) VALUES (10662, 'Borovnice zamrznjene vreč 2.5 kg');
INSERT INTO `test` (`id`, `name`) VALUES (16759, 'Borovnice zamrznjene vreč 2.5 kg');
INSERT INTO `test` (`id`, `name`) VALUES (22696, 'Borovničev liker 0,5 l');
INSERT INTO `test` (`id`, `name`) VALUES (22725, 'Borovničev liker 0,5 l');
INSERT INTO `test` (`id`, `name`) VALUES (22695, 'Borovničev liker 1 l');
INSERT INTO `test` (`id`, `name`) VALUES (22723, 'Borovničev liker 1 l');
INSERT INTO `test` (`id`, `name`) VALUES (503, 'Borovničevec');
INSERT INTO `test` (`id`, `name`) VALUES (10336, 'Borovničevec  (25%) LBZ KZ Metlika');
INSERT INTO `test` (`id`, `name`) VALUES (6220, 'BOROVNIČEVEC 0.2L');
INSERT INTO `test` (`id`, `name`) VALUES (6188, 'BOROVNIČEVEC 0.7L KILC');
INSERT INTO `test` (`id`, `name`) VALUES (14694, 'Borovničevec Bahne z borovnicami (20%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (20791, 'Borovničevec Bahne z borovnicami (20%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (14695, 'Borovničevec Dana (20%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (20792, 'Borovničevec Dana (20%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (14696, 'Borovničevec Dana (23%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (20793, 'Borovničevec Dana (23%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (6201, 'BOROVNIČEVEC DOMAČI  KEJŽAR 0.2l');
INSERT INTO `test` (`id`, `name`) VALUES (6198, 'BOROVNIČEVEC DOMAČI KEJŽAR 0.05L ');
INSERT INTO `test` (`id`, `name`) VALUES (14697, 'Borovničevec domači Kejžar stn 0.7L');
INSERT INTO `test` (`id`, `name`) VALUES (20794, 'Borovničevec domači Kejžar stn 0.7L');
INSERT INTO `test` (`id`, `name`) VALUES (14698, 'Borovničevec Fructal (20%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (20795, 'Borovničevec Fructal (20%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (14699, 'Borovničevec Karakal (24%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (20796, 'Borovničevec Karakal (24%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (14700, 'Borovničevec Metlika (25%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (20797, 'Borovničevec Metlika (25%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (14701, 'Borovničevec Mikelj  (20%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (20798, 'Borovničevec Mikelj  (20%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (14702, 'Borovničevec paradiso N4 japi (14.9%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (20799, 'Borovničevec paradiso N4 japi (14.9%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (6203, 'BOROVNIČEVEC PRESTIGE 23% MB3 1L');
INSERT INTO `test` (`id`, `name`) VALUES (14703, 'Borovničevec The Mengo trade (14.5%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (20800, 'Borovničevec The Mengo trade (14.5%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (14704, 'Borovničevec The Mengo Trade (23%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (20801, 'Borovničevec The Mengo Trade (23%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (6193, 'BOROVNIČEVEC ZALOŽNIK 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (6197, 'BOROVNIČOVEC.VILJAMOVKA DARILNI KOMPLET BV2');
INSERT INTO `test` (`id`, `name`) VALUES (2783, 'Bosa rosa - SIMCIC EDI');
INSERT INTO `test` (`id`, `name`) VALUES (271, 'Boss ');
INSERT INTO `test` (`id`, `name`) VALUES (16436, 'Božični okraski okenski 35 lučk zav 1 kos');
INSERT INTO `test` (`id`, `name`) VALUES (22533, 'Božični okraski okenski 35 lučk zav 1 kos');
INSERT INTO `test` (`id`, `name`) VALUES (10159, 'Brancin filet 80-125g zamrznjen');
INSERT INTO `test` (`id`, `name`) VALUES (10663, 'Brancin filet zamrznjen 100/150 škat 5kg');
INSERT INTO `test` (`id`, `name`) VALUES (16760, 'Brancin filet zamrznjen 100/150 škat 5kg');
INSERT INTO `test` (`id`, `name`) VALUES (10664, 'Brancin filet zamrznjen 120/170 škat 5kg');
INSERT INTO `test` (`id`, `name`) VALUES (16761, 'Brancin filet zamrznjen 120/170 škat 5kg');
INSERT INTO `test` (`id`, `name`) VALUES (10665, 'Brancin filet zamrznjen 80/120 škat 5kg');
INSERT INTO `test` (`id`, `name`) VALUES (16762, 'Brancin filet zamrznjen 80/120 škat 5kg');
INSERT INTO `test` (`id`, `name`) VALUES (3738, 'BRANDY DOMAČI ALKO 1L');
INSERT INTO `test` (`id`, `name`) VALUES (14705, 'Brandy domači Fructal (38%) pet 0.2L');
INSERT INTO `test` (`id`, `name`) VALUES (20802, 'Brandy domači Fructal (38%) pet 0.2L');
INSERT INTO `test` (`id`, `name`) VALUES (14706, 'Brandy domači Fructal (38%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (20803, 'Brandy domači Fructal (38%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (14707, 'Brandy domači Prima Badel (36%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (20804, 'Brandy domači Prima Badel (36%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (14708, 'Brandy Grand monet Badel (38%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (20805, 'Brandy Grand monet Badel (38%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (14709, 'Brandy Imperio de Jerez Solero (38%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (20806, 'Brandy Imperio de Jerez Solero (38%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (14710, 'Brandy Metaxa 3x (ad) (38%) stn 0.7L');
INSERT INTO `test` (`id`, `name`) VALUES (20807, 'Brandy Metaxa 3x (ad) (38%) stn 0.7L');
INSERT INTO `test` (`id`, `name`) VALUES (3749, 'BRANDY METAXA 5* 0.7L');
INSERT INTO `test` (`id`, `name`) VALUES (3747, 'BRANDY METAXA 5* 0.7L CLASIC');
INSERT INTO `test` (`id`, `name`) VALUES (14711, 'Brandy Metaxa 5x Classsic (38%) škat 0.7L');
INSERT INTO `test` (`id`, `name`) VALUES (20808, 'Brandy Metaxa 5x Classsic (38%) škat 0.7L');
INSERT INTO `test` (`id`, `name`) VALUES (3748, 'BRANDY METAXA 7* 0.7L');
INSERT INTO `test` (`id`, `name`) VALUES (14712, 'Brandy Metaxa Amphora (40%) škat 0.7L');
INSERT INTO `test` (`id`, `name`) VALUES (20809, 'Brandy Metaxa Amphora (40%) škat 0.7L');
INSERT INTO `test` (`id`, `name`) VALUES (3746, 'BRANDY NAPOLEON 0.7L');
INSERT INTO `test` (`id`, `name`) VALUES (14713, 'Brandy Osborne veterano (36%) stn 0.7L');
INSERT INTO `test` (`id`, `name`) VALUES (20810, 'Brandy Osborne veterano (36%) stn 0.7L');
INSERT INTO `test` (`id`, `name`) VALUES (3753, 'BRANDY SKENDERBERG 0.5L');
INSERT INTO `test` (`id`, `name`) VALUES (3737, 'BRANDY SKENDERBEU 0.5L');
INSERT INTO `test` (`id`, `name`) VALUES (3751, 'BRANDY SKENDERBEU 0.7L');
INSERT INTO `test` (`id`, `name`) VALUES (3750, 'BRANDY SKENDERBEU 40% 0.5L');
INSERT INTO `test` (`id`, `name`) VALUES (3755, 'BRANDY STOCK 0.7L');
INSERT INTO `test` (`id`, `name`) VALUES (3757, 'BRANDY STOCK 1L');
INSERT INTO `test` (`id`, `name`) VALUES (3758, 'BRANDY STOCK 38% 0.70L');
INSERT INTO `test` (`id`, `name`) VALUES (3759, 'BRANDY STOCK 84 0.03L');
INSERT INTO `test` (`id`, `name`) VALUES (14714, 'Brandy Stock 84 VSOP (38%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (20811, 'Brandy Stock 84 VSOP (38%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (14715, 'Brandy Stock 84 VSOP 20*0.03L(38%) zav 0.6L');
INSERT INTO `test` (`id`, `name`) VALUES (20812, 'Brandy Stock 84 VSOP 20*0.03L(38%) zav 0.6L');
INSERT INTO `test` (`id`, `name`) VALUES (14716, 'Brandy Stock XO (40%) stn 0.7L');
INSERT INTO `test` (`id`, `name`) VALUES (20813, 'Brandy Stock XO (40%) stn 0.7L');
INSERT INTO `test` (`id`, `name`) VALUES (3756, 'BRANDY STOCK XO EXTRA OLD  0.7L');
INSERT INTO `test` (`id`, `name`) VALUES (3754, 'BRANDY VECCHIA CLASSICA  0.7L');
INSERT INTO `test` (`id`, `name`) VALUES (3744, 'BRANDY VECCHIA EXTRA BRANDY 40% 0.10L');
INSERT INTO `test` (`id`, `name`) VALUES (14717, 'Brandy Vecchia Extra Dalmacijavino (38%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (20814, 'Brandy Vecchia Extra Dalmacijavino (38%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (14718, 'Brandy Vecchia riserva Sari (38%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (20815, 'Brandy Vecchia riserva Sari (38%) stn 1L');
INSERT INTO `test` (`id`, `name`) VALUES (14719, 'Brandy Vecchia romagna  Nera (38%) stn 0.70L');
INSERT INTO `test` (`id`, `name`) VALUES (20816, 'Brandy Vecchia romagna  Nera (38%) stn 0.70L');
INSERT INTO `test` (`id`, `name`) VALUES (3742, 'BRANDY VECCHIA ROMAGNA 1L');
INSERT INTO `test` (`id`, `name`) VALUES (3741, 'BRANDY VECCHIA ROMAGNA 38% 0.5L');
INSERT INTO `test` (`id`, `name`) VALUES (1040, 'brane');
INSERT INTO `test` (`id`, `name`) VALUES (14690, 'Breezer ananas (5%) stn 0.275L');
INSERT INTO `test` (`id`, `name`) VALUES (20787, 'Breezer ananas (5%) stn 0.275L');
INSERT INTO `test` (`id`, `name`) VALUES (7066, 'BREEZER BACARDI ANANAS 0.275 ST');
INSERT INTO `test` (`id`, `name`) VALUES (7067, 'BREEZER BACARDI GRENIVKA  0.275');
INSERT INTO `test` (`id`, `name`) VALUES (7065, 'BREEZER BACARDI LIMETA 0.275');
INSERT INTO `test` (`id`, `name`) VALUES (7068, 'BREEZER BACARDI LUBENICA 0.275');
INSERT INTO `test` (`id`, `name`) VALUES (7064, 'BREEZER BACARDI POMAR. 0.275 ST');
INSERT INTO `test` (`id`, `name`) VALUES (14691, 'Breezer grenivka (5%) stn 0.275L');
INSERT INTO `test` (`id`, `name`) VALUES (20788, 'Breezer grenivka (5%) stn 0.275L');
INSERT INTO `test` (`id`, `name`) VALUES (14692, 'Breezer limeta (5%) stn 0.275L');
INSERT INTO `test` (`id`, `name`) VALUES (20789, 'Breezer limeta (5%) stn 0.275L');
INSERT INTO `test` (`id`, `name`) VALUES (14693, 'Breezer pomaranča (5%) stn 0.275L');
INSERT INTO `test` (`id`, `name`) VALUES (20790, 'Breezer pomaranča (5%) stn 0.275L');
INSERT INTO `test` (`id`, `name`) VALUES (10666, 'Breskve sveže 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (16763, 'Breskve sveže 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (538, 'Brezalkoholno pivo-Bavaria malt');
INSERT INTO `test` (`id`, `name`) VALUES (900, 'Brezkofeinska kava');
INSERT INTO `test` (`id`, `name`) VALUES (10466, 'Brezorkavnik 953.59 (moški), 952.59 (ženski)');
INSERT INTO `test` (`id`, `name`) VALUES (10471, 'Brezorkavnik iz flisa KA913 (moški), KA906 (ženski)');
INSERT INTO `test` (`id`, `name`) VALUES (10470, 'Brezrokavnik softshell KA403 (moški), KA404 (ženski)');
INSERT INTO `test` (`id`, `name`) VALUES (3389, 'Brezžični alarmni sistem');
INSERT INTO `test` (`id`, `name`) VALUES (657, 'Brezžični alarmni sistem GSM300');
INSERT INTO `test` (`id`, `name`) VALUES (658, 'Brezžični hišni alarm ProGuard800 ');
INSERT INTO `test` (`id`, `name`) VALUES (15211, 'Briketi Horizont  lesni za žar vreč 3kg');
INSERT INTO `test` (`id`, `name`) VALUES (21308, 'Briketi Horizont  lesni za žar vreč 3kg');
INSERT INTO `test` (`id`, `name`) VALUES (6517, 'BRIKETI ŠPINAČNI 2.5KG');
INSERT INTO `test` (`id`, `name`) VALUES (486, 'Brinjevec');
INSERT INTO `test` (`id`, `name`) VALUES (3669, 'BRINJEVEC 38% 1L BAUER');
INSERT INTO `test` (`id`, `name`) VALUES (6192, 'BRINJEVEC ALKOBAP 1L');
INSERT INTO `test` (`id`, `name`) VALUES (6182, 'BRINJEVEC DANA 1L');
INSERT INTO `test` (`id`, `name`) VALUES (6185, 'BRINJEVEC PRESAD 1L');
INSERT INTO `test` (`id`, `name`) VALUES (6212, 'BRINJEVEC PRIOR 0.7L');
INSERT INTO `test` (`id`, `name`) VALUES (6186, 'BRINJEVEC S CVETNEGA VRTA 0.5L AB SAD');
INSERT INTO `test` (`id`, `name`) VALUES (6628, 'BRINOVE JAGODE 28G DROGA');
INSERT INTO `test` (`id`, `name`) VALUES (10667, 'Brinove jagode AKi vreč 100g');
INSERT INTO `test` (`id`, `name`) VALUES (16764, 'Brinove jagode AKi vreč 100g');
INSERT INTO `test` (`id`, `name`) VALUES (10668, 'Brinove jagode cele Droga UP koz 28g');
INSERT INTO `test` (`id`, `name`) VALUES (16765, 'Brinove jagode cele Droga UP koz 28g');
INSERT INTO `test` (`id`, `name`) VALUES (10669, 'Brinove jagode Kotanyi koz. 32g');
INSERT INTO `test` (`id`, `name`) VALUES (16766, 'Brinove jagode Kotanyi koz. 32g');
INSERT INTO `test` (`id`, `name`) VALUES (336, 'Brisača Hygenius eco');
INSERT INTO `test` (`id`, `name`) VALUES (7016, 'BRISAČA IND.BELA MAXI CARIND 2/1');
INSERT INTO `test` (`id`, `name`) VALUES (16444, 'Brisača MIKRO 50*90cm hipotal 1 kos');
INSERT INTO `test` (`id`, `name`) VALUES (22541, 'Brisača MIKRO 50*90cm hipotal 1 kos');
INSERT INTO `test` (`id`, `name`) VALUES (16445, 'Brisača MIKRO 70*140cm hipotal 1 kos');
INSERT INTO `test` (`id`, `name`) VALUES (22542, 'Brisača MIKRO 70*140cm hipotal 1 kos');
INSERT INTO `test` (`id`, `name`) VALUES (16446, 'Brisača Paloma papir. industrijska pet. 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (22543, 'Brisača Paloma papir. industrijska pet. 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (6989, 'BRISAČA PAP. BELA KUH. PALOMA 23CM 4/1');
INSERT INTO `test` (`id`, `name`) VALUES (6982, 'BRISAČA PAPIR. BELA MEDIC. NEVT. PALOMA 58 CM');
INSERT INTO `test` (`id`, `name`) VALUES (16447, 'Brisača papirnata Soft Flower 2sl. bela zavit 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (22544, 'Brisača papirnata Soft Flower 2sl. bela zavit 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (16448, 'Brisača papirnata Soft Flower 2sl.bela rola160list');
INSERT INTO `test` (`id`, `name`) VALUES (22545, 'Brisača papirnata Soft Flower 2sl.bela rola160list');
INSERT INTO `test` (`id`, `name`) VALUES (16449, 'Brisača papirnata Soft Flower XXL 2sl.bela 300list');
INSERT INTO `test` (`id`, `name`) VALUES (22546, 'Brisača papirnata Soft Flower XXL 2sl.bela 300list');
INSERT INTO `test` (`id`, `name`) VALUES (16450, 'Brisača papirnata v roli 2.sl bela celuloza 100m');
INSERT INTO `test` (`id`, `name`) VALUES (22547, 'Brisača papirnata v roli 2.sl bela celuloza 100m');
INSERT INTO `test` (`id`, `name`) VALUES (6995, 'BRISAČA ROLA IND.BELA 2/1 ');
INSERT INTO `test` (`id`, `name`) VALUES (325, 'Brisača za podajalnik - Tork Matic');
INSERT INTO `test` (`id`, `name`) VALUES (6994, 'BRISAČE BELE MEDICINSKE MAXI SOFT ');
INSERT INTO `test` (`id`, `name`) VALUES (7015, 'BRISAČE BOBINA MULTI MODRA 3 SLOJNA 2/1');
INSERT INTO `test` (`id`, `name`) VALUES (6981, 'BRISAČE IND. PALOMA PROF. 2/1 BELE');
INSERT INTO `test` (`id`, `name`) VALUES (6980, 'BRISAČE IND. PALOMA PROF. 2/1 ROZA');
INSERT INTO `test` (`id`, `name`) VALUES (6968, 'BRISAČE KREP PALOMA ŽK 1P AP 100L 2/1 A24 ');
INSERT INTO `test` (`id`, `name`) VALUES (6983, 'BRISAČE KUHINJ. EXCLUSIVE 23CM 4/1 BE');
INSERT INTO `test` (`id`, `name`) VALUES (6988, 'BRISAČE KUHINJ. NATURA-BELA  23CM 2/1');
INSERT INTO `test` (`id`, `name`) VALUES (6987, 'BRISAČE KUHINJSKE EXCLUSIVE 2/1 BELE');
INSERT INTO `test` (`id`, `name`) VALUES (7004, 'BRISAČE KUHINJSKE SOFT 2/1');
INSERT INTO `test` (`id`, `name`) VALUES (6961, 'BRISAČE NATURA CIK-CAK 250L 24X23CM');
INSERT INTO `test` (`id`, `name`) VALUES (7005, 'BRISAČE PAP. BOBINA 2 SL. BELE KIMI 3KG');
INSERT INTO `test` (`id`, `name`) VALUES (7027, 'BRISAČE PAP. BOBINA MIKRO 2/1');
INSERT INTO `test` (`id`, `name`) VALUES (7003, 'BRISAČE PAP. KUHINJSKE BELE TOFFLY 2/1');
INSERT INTO `test` (`id`, `name`) VALUES (6967, 'BRISAČE PAP. ROZA PALOMA 30CM 2/1');
INSERT INTO `test` (`id`, `name`) VALUES (7000, 'BRISAČE PAP. TORK MATIC 2 SLOJ. 21CM KIMI KRT');
INSERT INTO `test` (`id`, `name`) VALUES (7008, 'BRISAČE PAP. ZELENE LABORPLAST 20/250 LISTIČEV');
INSERT INTO `test` (`id`, `name`) VALUES (6957, 'BRISAČE PAP.PREGIBNE SIVE 160KOMX15');
INSERT INTO `test` (`id`, `name`) VALUES (16451, 'Brisače papir. 1sl zložene bež paloma 250kos');
INSERT INTO `test` (`id`, `name`) VALUES (22548, 'Brisače papir. 1sl zložene bež paloma 250kos');
INSERT INTO `test` (`id`, `name`) VALUES (16452, 'Brisače papir. 1sl zložene Cik Cak zavit. 250kos');
INSERT INTO `test` (`id`, `name`) VALUES (22549, 'Brisače papir. 1sl zložene Cik Cak zavit. 250kos');
INSERT INTO `test` (`id`, `name`) VALUES (16453, 'Brisače papir. 2sl. kuh. ex. maxi bele Paloma 2/1');
INSERT INTO `test` (`id`, `name`) VALUES (22550, 'Brisače papir. 2sl. kuh. ex. maxi bele Paloma 2/1');
INSERT INTO `test` (`id`, `name`) VALUES (16454, 'Brisače papir. 2sl. kuh. maxi Tenerella zav. 1kos');
INSERT INTO `test` (`id`, `name`) VALUES (22551, 'Brisače papir. 2sl. kuh. maxi Tenerella zav. 1kos');
INSERT INTO `test` (`id`, `name`) VALUES (16455, 'Brisače papir. 2sl. kuh. Tenerella casa zav. 6kos');
INSERT INTO `test` (`id`, `name`) VALUES (22552, 'Brisače papir. 2sl. kuh. Tenerella casa zav. 6kos');
INSERT INTO `test` (`id`, `name`) VALUES (22553, 'Brisače papir. 2sl. kuh. Tenerella extra zav. 1kos');
INSERT INTO `test` (`id`, `name`) VALUES (22554, 'Brisače papir. 2sl. kuh. Tenerella maxi zav. 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (16458, 'Brisače papir. 2sl. Maxi 2x800 list.T-Top zav 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (22555, 'Brisače papir. 2sl. Maxi 2x800 list.T-Top zav 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (16459, 'Brisače papir. 3sl. kuh. Tenerella maxi zav. 1kos');
INSERT INTO `test` (`id`, `name`) VALUES (22556, 'Brisače papir. 3sl. kuh. Tenerella maxi zav. 1kos');
INSERT INTO `test` (`id`, `name`) VALUES (16460, 'Brisače papir. Austro.bela 22cm 2*plast.6/1');
INSERT INTO `test` (`id`, `name`) VALUES (22557, 'Brisače papir. Austro.bela 22cm 2*plast.6/1');
INSERT INTO `test` (`id`, `name`) VALUES (16461, 'Brisače papir. bele mehke UP Paloma zavit. 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (22558, 'Brisače papir. bele mehke UP Paloma zavit. 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (16462, 'Brisače papir. Bobina Multi Maxi modre zavit 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (22559, 'Brisače papir. Bobina Multi Maxi modre zavit 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (16463, 'Brisače papir. Bobina Soft Fl Maxi bele zavit 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (22560, 'Brisače papir. Bobina Soft Fl Maxi bele zavit 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (16464, 'Brisače papir. krep 29cm Lotos UP zavit 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (22561, 'Brisače papir. krep 29cm Lotos UP zavit 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (16465, 'Brisače papir. krep.žleb. bele 30cm Paloma UP 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (22562, 'Brisače papir. krep.žleb. bele 30cm Paloma UP 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (16466, 'Brisače papir. krep.žleb. roza 30cm Paloma 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (22563, 'Brisače papir. krep.žleb. roza 30cm Paloma 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (16467, 'Brisače papir. Lotos krep bela zavit 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (22564, 'Brisače papir. Lotos krep bela zavit 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (16468, 'Brisače papir. Lotos maxi 30cm/200m pet 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (22565, 'Brisače papir. Lotos maxi 30cm/200m pet 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (16469, 'Brisače papir. maxi 20cm*200m rde Lotos zavit 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (22566, 'Brisače papir. maxi 20cm*200m rde Lotos zavit 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (16470, 'Brisače papir.1sl zlože.stand. bež.zele.zav 250kom');
INSERT INTO `test` (`id`, `name`) VALUES (22567, 'Brisače papir.1sl zlože.stand. bež.zele.zav 250kom');
INSERT INTO `test` (`id`, `name`) VALUES (16471, 'Brisače papir.1sl.rola 20x35cm 270mMIDI Lotus zav6');
INSERT INTO `test` (`id`, `name`) VALUES (22568, 'Brisače papir.1sl.rola 20x35cm 270mMIDI Lotus zav6');
INSERT INTO `test` (`id`, `name`) VALUES (22569, 'Brisače papir.1sl.rola 20x35cm MIDI Reflex zav 6');
INSERT INTO `test` (`id`, `name`) VALUES (22570, 'Brisače papir.1sl.zloženke 25x23cm škat 20x250list');
INSERT INTO `test` (`id`, `name`) VALUES (22571, 'Brisače papir.1sl.zloženke 25x23cm škat 20x300list');
INSERT INTO `test` (`id`, `name`) VALUES (22572, 'Brisače papir.2.sl kozmet.bele Paloma zavit 100kos');
INSERT INTO `test` (`id`, `name`) VALUES (22573, 'Brisače papir.2sl zložene lucart Z 3960');
INSERT INTO `test` (`id`, `name`) VALUES (22574, 'Brisače papir.2sl.kuhinj.potiskane Merc.zavit 2kos');
INSERT INTO `test` (`id`, `name`) VALUES (22575, 'Brisače papir.2sl.rola 19.5x35cm Reflex MIDI zav 6');
INSERT INTO `test` (`id`, `name`) VALUES (16479, 'Brisače papir.2sl.role 19.5cm bele nextTurn zav 6k');
INSERT INTO `test` (`id`, `name`) VALUES (22576, 'Brisače papir.2sl.role 19.5cm bele nextTurn zav 6k');
INSERT INTO `test` (`id`, `name`) VALUES (16480, 'Brisače papir.2sl.role bele enMotionReces. zav6kos');
INSERT INTO `test` (`id`, `name`) VALUES (22577, 'Brisače papir.2sl.role bele enMotionReces. zav6kos');
INSERT INTO `test` (`id`, `name`) VALUES (16481, 'Brisače papir.2sl.zloženke 25x23cm škat 20x200list');
INSERT INTO `test` (`id`, `name`) VALUES (22578, 'Brisače papir.2sl.zloženke 25x23cm škat 20x200list');
INSERT INTO `test` (`id`, `name`) VALUES (16482, 'Brisače papir.2slojne Mercator maxi navitje 2/1');
INSERT INTO `test` (`id`, `name`) VALUES (22579, 'Brisače papir.2slojne Mercator maxi navitje 2/1');
INSERT INTO `test` (`id`, `name`) VALUES (16483, 'Brisače papir.zloženke 2sl. DailyGold zavit 230kos');
INSERT INTO `test` (`id`, `name`) VALUES (22580, 'Brisače papir.zloženke 2sl. DailyGold zavit 230kos');
INSERT INTO `test` (`id`, `name`) VALUES (16484, 'Brisače papirnate bele 2sl. Tenerella zav. 4kos');
INSERT INTO `test` (`id`, `name`) VALUES (22581, 'Brisače papirnate bele 2sl. Tenerella zav. 4kos');
INSERT INTO `test` (`id`, `name`) VALUES (7024, 'BRISAČE TENERABELLA PAP. 400/1');
INSERT INTO `test` (`id`, `name`) VALUES (7019, 'BRISAČE TENERELLA 800 LIST. 2/1');
INSERT INTO `test` (`id`, `name`) VALUES (7025, 'BRISAČE TENERELLA BIG 2SL. 2RX200L.');
INSERT INTO `test` (`id`, `name`) VALUES (7022, 'BRISAČE TENERELLA CASA DVOSL. 4/1');
INSERT INTO `test` (`id`, `name`) VALUES (7020, 'BRISAČE TENERELLA PAP.MAXI. 2RX100LIST. ');
INSERT INTO `test` (`id`, `name`) VALUES (7033, 'BRISAČE ZLOŽ. NATUR PAK 25X23CM  250/1');
INSERT INTO `test` (`id`, `name`) VALUES (6977, 'BRISAČE ZLOŽENE CLASSIC 250/1 BELE');
INSERT INTO `test` (`id`, `name`) VALUES (6975, 'BRISAČE ZLOŽENE CLASSIC 250/1 NARAVNE');
INSERT INTO `test` (`id`, `name`) VALUES (16485, 'Brisače zložene Hypa basic z-z 5000kos bele');
INSERT INTO `test` (`id`, `name`) VALUES (22582, 'Brisače zložene Hypa basic z-z 5000kos bele');
INSERT INTO `test` (`id`, `name`) VALUES (6992, 'BRISAČE ZLOŽENE PALOMA 150/1');
INSERT INTO `test` (`id`, `name`) VALUES (6996, 'BRISAČE ZLOŽENE STANDARD ZELENE 250/1');
INSERT INTO `test` (`id`, `name`) VALUES (6976, 'BRISAČE ZLOŽENE ZELENE PALOMA 250/1');
INSERT INTO `test` (`id`, `name`) VALUES (6958, 'BRISAČE ZLOŽENKE 5000/1');
INSERT INTO `test` (`id`, `name`) VALUES (6993, 'BRISAČE ZLOŽLJIVE PROF. SOFT BELE ');
INSERT INTO `test` (`id`, `name`) VALUES (16486, 'Brisalec tal + krpa za tla 40 cm Hipotal 1kos');
INSERT INTO `test` (`id`, `name`) VALUES (22583, 'Brisalec tal + krpa za tla 40 cm Hipotal 1kos');
INSERT INTO `test` (`id`, `name`) VALUES (16487, 'Brisalec tal + krpa za tla 60 cm Cisne kpl pvc1kos');
INSERT INTO `test` (`id`, `name`) VALUES (22584, 'Brisalec tal + krpa za tla 60 cm Cisne kpl pvc1kos');
INSERT INTO `test` (`id`, `name`) VALUES (16488, 'Brisalec tal + krpa za tla 60 cm Hipotal 1kos');
INSERT INTO `test` (`id`, `name`) VALUES (22585, 'Brisalec tal + krpa za tla 60 cm Hipotal 1kos');
INSERT INTO `test` (`id`, `name`) VALUES (16489, 'Brisalec tal PM ježek 40 ckm kpl');
INSERT INTO `test` (`id`, `name`) VALUES (22586, 'Brisalec tal PM ježek 40 ckm kpl');
INSERT INTO `test` (`id`, `name`) VALUES (16490, 'Brisalec tal univerzalni KPL 40 cm');
INSERT INTO `test` (`id`, `name`) VALUES (22587, 'Brisalec tal univerzalni KPL 40 cm');
INSERT INTO `test` (`id`, `name`) VALUES (16491, 'Brisalec tal univerzalni KPL 50 cm');
INSERT INTO `test` (`id`, `name`) VALUES (22588, 'Brisalec tal univerzalni KPL 50 cm');
INSERT INTO `test` (`id`, `name`) VALUES (16492, 'Brisalec tal za potisk vode 55cm + držalo 140cm 1k');
INSERT INTO `test` (`id`, `name`) VALUES (22589, 'Brisalec tal za potisk vode 55cm + držalo 140cm 1k');
INSERT INTO `test` (`id`, `name`) VALUES (16493, 'Brisalec za okno z gobo Hipotal kom');
INSERT INTO `test` (`id`, `name`) VALUES (22590, 'Brisalec za okno z gobo Hipotal kom');
INSERT INTO `test` (`id`, `name`) VALUES (16494, 'Brisalec za prah AttrActive Vileda 1kos');
INSERT INTO `test` (`id`, `name`) VALUES (22591, 'Brisalec za prah AttrActive Vileda 1kos');
INSERT INTO `test` (`id`, `name`) VALUES (16495, 'Brisalec za prah Pronto mini  škat 1kos');
INSERT INTO `test` (`id`, `name`) VALUES (22592, 'Brisalec za prah Pronto mini  škat 1kos');
INSERT INTO `test` (`id`, `name`) VALUES (16496, 'Brisalec za prah Spontex zavit 1kos');
INSERT INTO `test` (`id`, `name`) VALUES (22593, 'Brisalec za prah Spontex zavit 1kos');
INSERT INTO `test` (`id`, `name`) VALUES (16497, 'Brisalec za stekla');
INSERT INTO `test` (`id`, `name`) VALUES (22594, 'Brisalec za stekla');
INSERT INTO `test` (`id`, `name`) VALUES (16498, 'Brisalec za tla močo +pvc držalo Vileda 1kos');
INSERT INTO `test` (`id`, `name`) VALUES (22595, 'Brisalec za tla močo +pvc držalo Vileda 1kos');
INSERT INTO `test` (`id`, `name`) VALUES (15382, 'Britvice Mem super silver platinum zavit 5kos');
INSERT INTO `test` (`id`, `name`) VALUES (21479, 'Britvice Mem super silver platinum zavit 5kos');
INSERT INTO `test` (`id`, `name`) VALUES (15383, 'Brivnik Bic classic sensitive vreč 5kos');
INSERT INTO `test` (`id`, `name`) VALUES (21480, 'Brivnik Bic classic sensitive vreč 5kos');
INSERT INTO `test` (`id`, `name`) VALUES (15384, 'Brivnik Gillete blue 2 plus zavit 5 kos');
INSERT INTO `test` (`id`, `name`) VALUES (21481, 'Brivnik Gillete blue 2 plus zavit 5 kos');
INSERT INTO `test` (`id`, `name`) VALUES (15385, 'Brivnik Gillette Mach3 škat.8kom');
INSERT INTO `test` (`id`, `name`) VALUES (21482, 'Brivnik Gillette Mach3 škat.8kom');
INSERT INTO `test` (`id`, `name`) VALUES (15386, 'Brivnik ženski Bic Soleil clic z aloe škat 1 kos');
INSERT INTO `test` (`id`, `name`) VALUES (21483, 'Brivnik ženski Bic Soleil clic z aloe škat 1 kos');
INSERT INTO `test` (`id`, `name`) VALUES (5439, 'BRIZGANEC KOZJANSKI  FRUPI 1.5L PVC');
INSERT INTO `test` (`id`, `name`) VALUES (6427, 'BROKOLI  ZAMRZ.1.KL.2500 G LEDO');
INSERT INTO `test` (`id`, `name`) VALUES (6344, 'BROKOLI 1.KL. 2.5KG VREČ.');
INSERT INTO `test` (`id`, `name`) VALUES (6536, 'BROKOLI 40-60MM I.KV. 2.5KG ZM');
INSERT INTO `test` (`id`, `name`) VALUES (6534, 'BROKOLI IQF 2.5KG');
INSERT INTO `test` (`id`, `name`) VALUES (6535, 'BROKOLI IQF 2.5KG VREČ.');
INSERT INTO `test` (`id`, `name`) VALUES (6523, 'BROKOLI KAISER MIX 2.5KG LJUB.MLEKARNE');
INSERT INTO `test` (`id`, `name`) VALUES (6266, 'BROKOLI MIX 2.5KG');
INSERT INTO `test` (`id`, `name`) VALUES (10098, 'Brokoli zamrznjen 40-60mm ');
INSERT INTO `test` (`id`, `name`) VALUES (10670, 'Brokoli zamrznjen IQF 40-60mm  vreč 2.5kg');
INSERT INTO `test` (`id`, `name`) VALUES (16767, 'Brokoli zamrznjen IQF 40-60mm  vreč 2.5kg');
INSERT INTO `test` (`id`, `name`) VALUES (3035, 'Bronast čajnik cedilo');
INSERT INTO `test` (`id`, `name`) VALUES (2443, 'Brouilly 2009 - DOMAINE RUET');
INSERT INTO `test` (`id`, `name`) VALUES (5125, 'BROZINA DOMAČI PRŠUT BK');
INSERT INTO `test` (`id`, `name`) VALUES (5126, 'BROZINA DOMAČI PRŠUT S KOSTJO');
INSERT INTO `test` (`id`, `name`) VALUES (7160, 'BROZINA DOMAČI ZAŠINEK V.P.');
INSERT INTO `test` (`id`, `name`) VALUES (7161, 'BROZINA MILANSKA SALAMA');
INSERT INTO `test` (`id`, `name`) VALUES (5130, 'BROZINA PRŠUT DELIKATESNI DOMAČI BK');
INSERT INTO `test` (`id`, `name`) VALUES (5128, 'BROZINA PRŠUT KUHAN');
INSERT INTO `test` (`id`, `name`) VALUES (6514, 'BRSTIČNI OHROVT 2.5KG ZM');
INSERT INTO `test` (`id`, `name`) VALUES (2666, 'Brunello di Montalcino - PICCINI');
INSERT INTO `test` (`id`, `name`) VALUES (8544, 'BRUSNICE SUHE 125G  SEEBERGER');
INSERT INTO `test` (`id`, `name`) VALUES (7739, 'BRUSNICE SUHE BIMED 100G');
INSERT INTO `test` (`id`, `name`) VALUES (10671, 'Brusnice suhe ML pet 150 g');
INSERT INTO `test` (`id`, `name`) VALUES (16768, 'Brusnice suhe ML pet 150 g');
INSERT INTO `test` (`id`, `name`) VALUES (10672, 'Brusnice suhe pet na dan pet 125 g');
INSERT INTO `test` (`id`, `name`) VALUES (16769, 'Brusnice suhe pet na dan pet 125 g');
INSERT INTO `test` (`id`, `name`) VALUES (2655, 'Brut Imperial - MOET&CHANDON');
INSERT INTO `test` (`id`, `name`) VALUES (2913, 'Brut Nature - DRAPPIER');
INSERT INTO `test` (`id`, `name`) VALUES (7086, 'BUČKE');
INSERT INTO `test` (`id`, `name`) VALUES (7140, 'BUČKE SVEŽE 1KG');
INSERT INTO `test` (`id`, `name`) VALUES (10673, 'Bučke sveže 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (16770, 'Bučke sveže 1kg');
INSERT INTO `test` (`id`, `name`) VALUES (9059, 'BUČNA JEDRCA 680G  KOTANY');
INSERT INTO `test` (`id`, `name`) VALUES (10674, 'Bučna semena cela posušena Kotanyi pet 680g');
INSERT INTO `test` (`id`, `name`) VALUES (16771, 'Bučna semena cela posušena Kotanyi pet 680g');
INSERT INTO `test` (`id`, `name`) VALUES (7516, 'BUČNE GOLICE NARAVNO SUŠENE 150G');
INSERT INTO `test` (`id`, `name`) VALUES (10675, 'Bučne golice pražene odlično vreč 100 g');
INSERT INTO `test` (`id`, `name`) VALUES (16772, 'Bučne golice pražene odlično vreč 100 g');
INSERT INTO `test` (`id`, `name`) VALUES (7805, 'BUČNICE FRUTO PRAŽENE 70 G');
INSERT INTO `test` (`id`, `name`) VALUES (8081, 'BUČNICE FRUTO PRAŽENE 70G');
INSERT INTO `test` (`id`, `name`) VALUES (10676, 'Bučno seme oluščeno Natura vreč 300g');
INSERT INTO `test` (`id`, `name`) VALUES (16773, 'Bučno seme oluščeno Natura vreč 300g');
INSERT INTO `test` (`id`, `name`) VALUES (244, 'Budweiser Češki');
INSERT INTO `test` (`id`, `name`) VALUES (282, 'Buffet in Catering');
INSERT INTO `test` (`id`, `name`) VALUES (4676, 'BULL DOG 0.25 PLOČ.');
INSERT INTO `test` (`id`, `name`) VALUES (7312, 'BUNKA POHORSKA VP 1KG STRAŠEK');
INSERT INTO `test` (`id`, `name`) VALUES (2841, 'Burja - SUTOR');
INSERT INTO `test` (`id`, `name`) VALUES (4678, 'BURN 0.25 PLOČ.');
INSERT INTO `test` (`id`, `name`) VALUES (13882, 'Burn 4+2gratis šestorček 6 x 0.25L');
INSERT INTO `test` (`id`, `name`) VALUES (19979, 'Burn 4+2gratis šestorček 6 x 0.25L');
INSERT INTO `test` (`id`, `name`) VALUES (4679, 'BURN 6X0.25L PLOČ.');
INSERT INTO `test` (`id`, `name`) VALUES (13883, 'Burn ploč. 0.25L');
INSERT INTO `test` (`id`, `name`) VALUES (19980, 'Burn ploč. 0.25L');
INSERT INTO `test` (`id`, `name`) VALUES (4034, 'BUT. BAGUERI CONTESSE 1.5L');
INSERT INTO `test` (`id`, `name`) VALUES (3762, 'BUT. BELI PINO 0.7 ARH.63 ORMOŽ');
INSERT INTO `test` (`id`, `name`) VALUES (3975, 'BUT. BELI PINOT KRŠKO 0.75L ');
INSERT INTO `test` (`id`, `name`) VALUES (3922, 'BUT. BELI PINOT ORMOŽ 0.75L ');
INSERT INTO `test` (`id`, `name`) VALUES (3932, 'BUT. BELI PINOT PT.A. ORMOŽ 0.7L ');
INSERT INTO `test` (`id`, `name`) VALUES (4029, 'BUT. BELI PINOT QUERCUS 0.20');
INSERT INTO `test` (`id`, `name`) VALUES (4049, 'BUT. BELI PINOT QUERCUS 0.75L ');
INSERT INTO `test` (`id`, `name`) VALUES (3996, 'BUT. BELI PINOT RONK 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3889, 'BUT. BELI PINOT SUH PULLUS 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3816, 'BUT. BLANC DE BLANC J.P.CHENET 0.7L');
INSERT INTO `test` (`id`, `name`) VALUES (6001, 'BUT. BYB-CAMPO V. CRIANZA  0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (4104, 'BUT. BYB-SENORIO DE  VAL CRIANSA 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (4107, 'BUT. BYB-SENORIO DE ROBLES RED 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (4105, 'BUT. BYB-SENORIO DE ROBLES RESERVA 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (4108, 'BUT. BYB-SENORIO DE VAL RESERVA 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (4106, 'BUT. BYB-SENORIO DEL CONDESTABLE RED 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3770, 'BUT. CAB. SAVVIGNON ČARGA 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (4053, 'BUT. CABERERNET SAUVIG. QUERCUS 0.75L ');
INSERT INTO `test` (`id`, `name`) VALUES (3913, 'BUT. CABERNET CAPRIS SAUVIGNON 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (4003, 'BUT. CABERNET FRANC RONK 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3775, 'BUT. CABERNET SAUIGNON ZARO 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (4046, 'BUT. CABERNET SAUV.BAGUERI  0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3905, 'BUT. CABERNET SAUVI  VINAKOPER 0.75');
INSERT INTO `test` (`id`, `name`) VALUES (3851, 'BUT. CABERNET SAUVI. VENTUS  VIPAVA 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3916, 'BUT. CABERNET SAUVIG. CAPO D ISTRIA 0.75 VINAKOPER');
INSERT INTO `test` (`id`, `name`) VALUES (3909, 'BUT. CABERNET SAUVIG.CAPO D`ISTRIA 0.75  VINAKOPER');
INSERT INTO `test` (`id`, `name`) VALUES (4002, 'BUT. CABERNET SAUVIGNON RONK 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3872, 'BUT. CABERNET SAUVIGNON SU.V. 99 BRDA');
INSERT INTO `test` (`id`, `name`) VALUES (3857, 'BUT. CABERNET SAUVIGNON VIPAVA 1.5L ');
INSERT INTO `test` (`id`, `name`) VALUES (4103, 'BUT. CAMPO VIEJO RESERVA 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3911, 'BUT. CAPRIS MALVAZIJA 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3915, 'BUT. CAPRIS PENEČE 0.7L');
INSERT INTO `test` (`id`, `name`) VALUES (3912, 'BUT. CAPRIS REFOŠK 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (4088, 'BUT. CASILLERO CARMENERE 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3854, 'BUT. CHARDONNAY "VENTUS"  VIPAVA 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (4060, 'BUT. CHARDONNAY 0.75 LJUTOMER');
INSERT INTO `test` (`id`, `name`) VALUES (3987, 'BUT. CHARDONNAY 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3988, 'BUT. CHARDONNAY 0.75L SLOMŠEK');
INSERT INTO `test` (`id`, `name`) VALUES (4067, 'BUT. CHARDONNAY 2006 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3882, 'BUT. CHARDONNAY 98 EXCLUSIVE PTUJ 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3977, 'BUT. CHARDONNAY 99  KRŠKO 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (4042, 'BUT. CHARDONNAY BAGUERI 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3771, 'BUT. CHARDONNAY ČARGA 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3792, 'BUT. CHARDONNAY GLAVINIČ PT 0.75');
INSERT INTO `test` (`id`, `name`) VALUES (3956, 'BUT. CHARDONNAY KAPELA 0.75 L.2008');
INSERT INTO `test` (`id`, `name`) VALUES (3902, 'BUT. CHARDONNAY LABOR VINAKOPER 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3877, 'BUT. CHARDONNAY NOBLESSE 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3925, 'BUT. CHARDONNAY ORMOŽ 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3766, 'BUT. CHARDONNAY PT L.93 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (4048, 'BUT. CHARDONNAY QUERCUS 0.75L ');
INSERT INTO `test` (`id`, `name`) VALUES (3901, 'BUT. CHARDONNAY RICORVO VINAKOPER 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3998, 'BUT. CHARDONNAY RONK 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3992, 'BUT. CHARDONNAY SUHO 0.75 KLET BISTRICA');
INSERT INTO `test` (`id`, `name`) VALUES (3881, 'BUT. CHARDONNAY T.V. 2004 PTUJ 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3968, 'BUT. CHARDONNAY V.KRAS 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (4041, 'BUT. CHARDONNAY VILLA BRICI 0.75L ');
INSERT INTO `test` (`id`, `name`) VALUES (4005, 'BUT. CHATEAU COUTET 14% 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (4006, 'BUT. CHATEAU D  ARMAILHAC 12.5% 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (4096, 'BUT. CHIANTI 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3818, 'BUT. CO.LACLIE V.S.O.P.');
INSERT INTO `test` (`id`, `name`) VALUES (3970, 'BUT. CVIČEK KRŠKO 0.75 ');
INSERT INTO `test` (`id`, `name`) VALUES (4017, 'BUT. CVIČEK OD FARE 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (4015, 'BUT. CVIČEK ZAJC 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (4075, 'BUT. DINGAČ BADEL 0.75L ');
INSERT INTO `test` (`id`, `name`) VALUES (4077, 'BUT. DINGAČ MATUŠKO POTOMJE 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3985, 'BUT. DULCIS BRIŠKO BELO 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3986, 'BUT. DULCIS RDEČE 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3763, 'BUT. ERZETIČ ROSE DAMSKI POLSUHO 2007 0.7L');
INSERT INTO `test` (`id`, `name`) VALUES (3774, 'BUT. GAJA-PROMIS 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (4012, 'BUT. GAUBE KERNER 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (4084, 'BUT. GRAFFIGNA CENTENARIO MALBEC 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (4085, 'BUT. GRAFFIGNA MALBEC 0.7L');
INSERT INTO `test` (`id`, `name`) VALUES (4025, 'BUT. GRAJSKI BISER BREŽICE 0.75');
INSERT INTO `test` (`id`, `name`) VALUES (3776, 'BUT. GUERILA BELO 2006 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3777, 'BUT. GUERILA CUBA 2006 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3778, 'BUT. GUERILA PINELA 2007 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3793, 'BUT. GUERILA RISERVA 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3779, 'BUT. GUERILA ROSE 2006 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3780, 'BUT. GUERILA ZELEN 2006 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3938, 'BUT. HOLERMUS CHARDONAY 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3952, 'BUT. HOLERMUS CHARDONNAY BEST SELECTION 0.75L ');
INSERT INTO `test` (`id`, `name`) VALUES (3939, 'BUT. HOLERMUS LAŠKI RIZLING 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3944, 'BUT. HOLERMUS RANINA 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3941, 'BUT. HOLERMUS RENSKI RIZLING 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3942, 'BUT. HOLERMUS SAUVIGNON 0.75L');
INSERT INTO `test` (`id`, `name`) VALUES (3947, 'BUT. HOLERMUS SAUVIGNON BEST SELECTION 0.75L ');
INSERT INTO `test` (`id`, `name`) VALUES (3937, 'BUT. HOLERMUS ŠIPON 0.75L');
